### ISSUE TITLE
startcom对AIMP的证书被误杀？

### ISSUE THREAD

**Issue by EMLVIRUS** [chengr28/RevokeChinaCerts#101]
startcom对AIMP作者Artem Izmaylov的个人证书
![image](https://cloud.githubusercontent.com/assets/16912240/24585862/f4d23aaa-17c6-11e7-89d9-8bc481533f66.png)

指纹 ‎97 a5 4b 58 f8 e3 df 1f 4a ad 5a 77 e5 1c de ce b8 b7 fe 8f

奇怪的是证书是在执行online.bat的时候被吊销

**Comment by chengr28** [comment]
https://github.com/chengr28/RevokeChinaCerts/wiki/ReadMe_Online
StartCom 的根证书的确是在 Extended 版本里被吊销的，根证书被吊销，那么由根证书签发的下级证书自然不会被信任……
