### ISSUE TITLE
希望能通过增加参数使 bat 脚本全自动完成

### ISSUE THREAD

**Issue by 12425** [chengr28/RevokeChinaCerts#102]
希望能通过参数使脚本能够被添加到任务计划中自动执行。谢谢！
如：`RevokeChinaCerts_Online.bat -extended`

**Comment by chengr28** [comment]
感谢反馈，已经为 Windows 版本的所有批处理添加外挂参数支持，具体情况就是：
* 在参数后添加该批处理文件对应操作的数字编号就能指定所需要实现的功能，不需要输入任何字符
* 例如使用 `RevokeChinaCerts_Online.bat 2` 就是吊销 Extended 版本的证书
* 部分批处理（CodeSigning 和 Organization）如果需要选择是否使用 `SoftCertPolicyAppender` 在外挂参数模式下会自动选择不启用
* 部分批处理（Online Firefox）如果可以指定操作便携版本或安装版本的证书数据库的，在外挂参数模式下会自动选择安装版本
