### ISSUE TITLE
影响visual studio 2017 python组件安装

### ISSUE THREAD

**Issue by xxooxxooxx** [chengr28/RevokeChinaCerts#103]
python安装包使用了StartCom的CA,，由于运行此脚本后为吊销状态，会导致visual studio 2017 安装python组件，总是验证失败。

**Comment by chengr28** [comment]
https://github.com/chengr28/RevokeChinaCerts/wiki/ReadMe_Online
StartCom 的根证书的确是在 Extended 版本里被吊销的，根证书被吊销，那么由根证书签发的下级证书自然不会被信任……如果确实不想吊销这个证书，可以先还原所有更改，然后有两种方法：
- 使用 Base 版本
- 根据列表中证书的 Hash 值，到 `\Shared\Certificates` 中将对应值的文件删除
