### ISSUE TITLE
希望增加 Pale Moon 支持

### ISSUE THREAD

**Issue by 12425** [chengr28/RevokeChinaCerts#104]
[Pale Moon](https://www.palemoon.org/) 是一个衍生于 Firefox 的浏览器，配置文件的路径为
`%APPDATA%\Moonchild Productions\Pale Moon\Profiles`

实测将 `RevokeChinaCerts_Firefox.bat` 中三处
`%APPDATA%\Mozilla\Firefox\Profiles` 替换为上面的路径即可。

谢谢！

**Comment by chengr28** [comment]
不知道你使用的时候有没有留意屏幕上提示的信息？实际上 Firefox 的版本一直自带有指定证书数据库文件位置的功能，因为不可能给所有衍生尤其是便携版本做适配，所以这个只能依靠用户自行指定，当然把所有自带路径替换掉也是可以的。提示信息内容：
```
Revoke certificates in installed Firefox profile? [Y/N]
When you choose N:
* Certificates in portable Firefox profile will be revoked.
* Enter portable profile path, like "C:\Firefox\Data\profile" without quotes.
* The profile directory must include cert8.db database file.
```
