### ISSUE TITLE
FF 用户目录带空格时报错

### ISSUE THREAD

**Issue by EMLVIRUS** [chengr28/RevokeChinaCerts#105]
![image](https://user-images.githubusercontent.com/16912240/27039408-76439210-4fc0-11e7-8118-9c67427fd134.png)

全部都报为此错误，确认 FF 为安装版而且并未吊销任何证书；批处理确认为管理员权限运行

**Comment by chengr28** [comment]
这个看起来是批处理生成证书列表的时候出了问题。可以试试：
- 不要使用 git 而是从 GitHub 网站上 Download ZIP 获取本工具
- 不要使用管理员权限运行，Firefox 配置文件所在目录应该是不需要管理员权限也能访问的

**Comment by EMLVIRUS** [comment]
> 不要使用 git 而是从 GitHub 网站上 Download ZIP 获取本工具

本来也是这么获取的

> 不要使用管理员权限运行

仍旧是一样的报错

**Comment by chengr28** [comment]
那建议重新下一份，把现在这份删掉再试试。如果 Beta 版和正式版本的配置文件夹位置是一样的话，从图上看应该是对证书目录的读取有问题，工具里附带的证书名称不是这样的。

**Comment by EMLVIRUS** [comment]
明早我试试 寝室停电了 很尴尬。。。

**Comment by EMLVIRUS** [comment]
>  Beta 版和正式版本的配置文件夹位置

是一样的 beta release nightly 共享配置

重下一份还是一样的报错。。。。。。。。。。。。

**Comment by wongsyrone** [comment]
`set Certificates="%~dp0..\Shared\Certificates`

最后少了个引号

**Comment by EMLVIRUS** [comment]
加上引号变成这样
![image](https://user-images.githubusercontent.com/16912240/27113995-16ce809a-50f3-11e7-9f15-8455079d7907.png)

手动输入目录位置变成：
![image](https://user-images.githubusercontent.com/16912240/27114057-77cbfc88-50f3-11e7-9cdf-c9d72da9dc7f.png)

（我是复制粘贴的目录）

**Comment by chengr28** [comment]
@wongsyrone 这里这个变量的确是没有引号的，因为对后面连接字符串的操作有不利的影响，所以引号的另一半在串接的时候才会加上。

**Comment by chengr28** [comment]
研究了一下，发现是因为批处理处理这种带空格的路径（正式版本的 Firefox 似乎不会有这种情况）出错导致的，这边修复了一下，不过慎重起见希望 @EMLVIRUS 提供一下邮箱地址，这边提供修复后的批处理试试，谢谢。

**Comment by EMLVIRUS** [comment]
[emal](mailto:EMLVIRUS@outlook.com)

**Comment by EMLVIRUS** [comment]
刚刚的修复版确认修复

**Comment by chengr28** [comment]
已经放上来了，感谢反馈。
