### ISSUE TITLE
Firefox火狐报错呢

### ISSUE THREAD

**Issue by theratlesnake** [chengr28/RevokeChinaCerts#106]
![firefox1111111](https://user-images.githubusercontent.com/24611087/27048231-9d9750b4-4fdd-11e7-90db-e339fd9d15ee.jpg)
请问一下，我清除系统内置证书没问题，但是清理火狐的时候，运行批处理选2，报这个错误，请问是系统的错误，还是批处理的错误呢》？

**Comment by chengr28** [comment]
选择操作之前屏幕上应该有一段话，请务必先认真查看：
```
All revoking require Microsoft Visual C++ Redistributable 2015 x86 version.
```

**Comment by theratlesnake** [comment]
噢噢，看了下我的VC++还是2012的，看来是太低了

**Comment by chengr28** [comment]
VC++ 运行库版本之间不向下兼容，32 位和 64 位之间也是不兼容的，所以最好还是根据提示来装，或者干脆把全部版本都装一遍……

**Comment by theratlesnake** [comment]
我在3DM下载安装了VC++2015 32位的已经操作成功了（没安装64位的，系统是win7，64位），终于不怕CNNIC流氓了。
另外问下，那个【Windows 系统证书列表升级】这个可以不管吧？看不懂是什么意思，还有tor的火狐证书要执行操作吗？

**Comment by duiii** [comment]
也是这个错误。装了2015搞定。
然后运行firefox.bat，直接完成了，啥都没，这意思是我firefox里是干净的么？
![sp170614_074628](https://user-images.githubusercontent.com/28379772/27110046-2bbc7418-50d9-11e7-83fa-8cb632327df8.png)

**Comment by chengr28** [comment]
@theratlesnake Update 那个版本是用于给系统自带证书库升级的，但实际上对于 Windows 来说碰到自带证书库没有的证书也会自动去 Microsoft 的服务器获取，实际上并没有问题。至于 Tor 的 Firefox 这个不好说，理论上应该也是需要的，建议根据提示找到 Profile 目录手动输入到批处理中处理。

**Comment by chengr28** [comment]
@duiii Firefox 自带的那个工具没有回显，所以运行的时候如果没有出错就不会输出任何信息……如果确实不放心，可以到 Firefox 的选项页面检查证书吊销状态。

**Comment by theratlesnake** [comment]
@chengr28 谢谢
