### ISSUE TITLE
要不要单独加个证书清单来专门拒绝国产iOS助手类应用？

### ISSUE THREAD

**Issue by ShikiSuen** [chengr28/RevokeChinaCerts#107]
我是在想，这样一来就可以方便各位维护在使用 iPhone / iPad 的家人的电脑了，至少他们除了 iTunes 啥也装不上去。

我目前弄了个懒人包，但我想我是断无充足的时间去维护的，所以在想要不要交给你们：
https://app.box.com/s/xl5rc7b5kii28q18yk45juypay4elrrt

**Comment by ShikiSuen** [comment]
哦对了，要不要将这套单独独立为一个 GitHub Repo，毕竟这套件的目标群体可能还需要正常访问并使用其他依赖于国产证书的服务。

**Comment by chengr28** [comment]
『该共享文件或文件夹已被移除』

**Comment by chengr28** [comment]
其实这类针对 Apple 移动设备系统在 PC 上对应的软件证书，可以归类到 CodeSigning 版本的批处理的，不过主要还是得看看具体是什么类型的证书。需要注意的是，本工具不能吊销 iOS 平台的证书。

**Comment by ShikiSuen** [comment]
<img width="531" alt="2017-06-15 19 52 15" src="https://user-images.githubusercontent.com/3164826/27184497-2a62f8e0-5204-11e7-8a19-cfdaec55d435.png">
只要吊销 PC 端的就可以。

**Comment by chengr28** [comment]
看起来不登录就看不到？不如直接发邮箱算了……

**Comment by ShikiSuen** [comment]
可能与网域有关，我这边用 CMD+SHIFT+N 开启的 SAFARI 私隐浏览模式可以正常访问。

**Comment by chengr28** [comment]
已经弄回来了，的确和地域有关……有些地区能直接下，有些地区看不到文件。稍微看了一下，其实有一半以上都有了的，这里面只有 5 个没有（[CodeSigning 证书列表](https://github.com/chengr28/RevokeChinaCerts/wiki/ReadMe_CodeSigning_Organization)）下次更新应该会加上……

**Comment by ShikiSuen** [comment]
谢谢。我记得里面有一些快过期了的，届时可能得去下载那些助手的安装包来现扒新版的证书。

**Comment by chengr28** [comment]
已经添加到 CodeSigning 里了，感谢反馈。
