### ISSUE TITLE
I am a linux starter. Not sure how to use it, but it said to send you this.

### ISSUE THREAD

**Issue by a316323** [chengr28/RevokeChinaCerts#109]
root@X:/home/X/Downloads/RevokeChinaCerts-master/Linux# sudo ./revoke-china-certs.sh extended ~/.pki/nssdb
Generating EXTENDED CRL set
Resetting CA set
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
Revoking CAs in /root/.pki/nssdb/cert{8,9}.db
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
Done
Clearing symlinks in /etc/ssl/certs...
done.
Updating certificates in /etc/ssl/certs...
170 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Warn! Questionable certificates still exist on your system.

Please report a bug at:
https://github.com/chengr28/RevokeChinaCerts/issues

Please attach the following output:

Fingerprint=16:32:47:8D:89:F9:21:3A:92:00:85:63:F5:A4:A7:D3:12:40:8A:D6 SHA1 /etc/ssl/certs/WoSign_China.pem SHA1 Shared/Certificates/1632478D89F9213A92008563F5A4A7D312408AD6.crt
Fingerprint=31:F1:FD:68:22:63:20:EE:C6:3B:3F:9D:EA:4A:3E:53:7C:7C:39:17 SHA1 /etc/ssl/certs/StartCom_Certification_Authority_G2.pem SHA1 Shared/Certificates/31F1FD68226320EEC63B3F9DEA4A3E537C7C3917.crt
Fingerprint=3E:2B:F7:F2:03:1B:96:F3:8C:E6:C4:D8:A8:5D:3E:2D:58:47:6A:0F SHA1 /etc/ssl/certs/StartCom_Certification_Authority.pem SHA1 Shared/Certificates/3E2BF7F2031B96F38CE6C4D8A85D3E2D58476A0F.crt
Fingerprint=A3:F1:33:3F:E2:42:BF:CF:C5:D1:4E:8F:39:42:98:40:68:10:D1:A0 SHA1 /etc/ssl/certs/StartCom_Certification_Authority_2.pem SHA1 Shared/Certificates/A3F1333FE242BFCFC5D14E8F394298406810D1A0.crt
Fingerprint=B9:42:94:BF:91:EA:8F:B6:4B:E6:10:97:C7:FB:00:13:59:B6:76:CB SHA1 /etc/ssl/certs/WoSign.pem SHA1 Shared/Certificates/B94294BF91EA8FB64BE61097C7FB001359B676CB.crt
Fingerprint=D2:7A:D2:BE:ED:94:C0:A1:3C:C7:25:21:EA:5D:71:BE:81:19:F3:2B SHA1 /etc/ssl/certs/CA_WoSign_ECC_Root.pem SHA1 Shared/Certificates/D27AD2BEED94C0A13CC72521EA5D71BE8119F32B.crt
Fingerprint=FB:ED:DC:90:65:B7:27:20:37:BC:55:0C:9C:56:DE:BB:F2:78:94:E1 SHA1 /etc/ssl/certs/Certification_Authority_of_WoSign_G2.pem SHA1 Shared/Certificates/FBEDDC9065B7272037BC550C9C56DEBBF27894E1.crt

root@X:/home/X/Downloads/RevokeChinaCerts-master/Linux# ./validator.sh
---------------------
Beginning base tests.
---------------------
✓ https://211.146.10.133/
✓ https://wacc.n.shifen.com/

2 passing
0 failing
0 skipping
-------------------------
Beginning extended tests.
-------------------------
✓ https://cstest.cfca.com.cn/
✓ https://cs.cfca.com.cn/
✓ https://www.gdca.com.cn/
✗ https://root1evtest.wosign.com/
✗ https://root2evtest.wosign.com/
✗ https://www.wosign.com/
✗ https://www.sheca.com/
✗ https://www.startcom.org/
? https://root4evtest.wosign.com/
? https://root5evtest.wosign.com/
└── wget: (4) failed: Connection timed out.
└── wget: (4) failed: Connection timed out.

3 passing
5 failing
2 skipping
--------------------
Beginning all tests.
--------------------
✓ https://kyfw.12306.cn/
✗ https://epki.com.tw/
✗ https://www.hongkongpost.hk/
✗ https://www.twca.com.tw/

1 passing
3 failing
0 skipping
-------------------
All tests executed.

**Comment by a316323** [comment]
root@X:/home/X/Downloads/RevokeChinaCerts-master/Linux# ./revoke-china-certs.sh extended $HOME/.pki/nssdb
Generating EXTENDED CRL set
Resetting CA set
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
Revoking CAs in /root/.pki/nssdb/cert{8,9}.db
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
Done
Clearing symlinks in /etc/ssl/certs...
done.
Updating certificates in /etc/ssl/certs...
170 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Warn! Questionable certificates still exist on your system.

Please report a bug at:
https://github.com/chengr28/RevokeChinaCerts/issues

Please attach the following output:

Fingerprint=16:32:47:8D:89:F9:21:3A:92:00:85:63:F5:A4:A7:D3:12:40:8A:D6 SHA1 /etc/ssl/certs/WoSign_China.pem SHA1 Shared/Certificates/1632478D89F9213A92008563F5A4A7D312408AD6.crt
Fingerprint=31:F1:FD:68:22:63:20:EE:C6:3B:3F:9D:EA:4A:3E:53:7C:7C:39:17 SHA1 /etc/ssl/certs/StartCom_Certification_Authority_G2.pem SHA1 Shared/Certificates/31F1FD68226320EEC63B3F9DEA4A3E537C7C3917.crt
Fingerprint=3E:2B:F7:F2:03:1B:96:F3:8C:E6:C4:D8:A8:5D:3E:2D:58:47:6A:0F SHA1 /etc/ssl/certs/StartCom_Certification_Authority.pem SHA1 Shared/Certificates/3E2BF7F2031B96F38CE6C4D8A85D3E2D58476A0F.crt
Fingerprint=A3:F1:33:3F:E2:42:BF:CF:C5:D1:4E:8F:39:42:98:40:68:10:D1:A0 SHA1 /etc/ssl/certs/StartCom_Certification_Authority_2.pem SHA1 Shared/Certificates/A3F1333FE242BFCFC5D14E8F394298406810D1A0.crt
Fingerprint=B9:42:94:BF:91:EA:8F:B6:4B:E6:10:97:C7:FB:00:13:59:B6:76:CB SHA1 /etc/ssl/certs/WoSign.pem SHA1 Shared/Certificates/B94294BF91EA8FB64BE61097C7FB001359B676CB.crt
Fingerprint=D2:7A:D2:BE:ED:94:C0:A1:3C:C7:25:21:EA:5D:71:BE:81:19:F3:2B SHA1 /etc/ssl/certs/CA_WoSign_ECC_Root.pem SHA1 Shared/Certificates/D27AD2BEED94C0A13CC72521EA5D71BE8119F32B.crt
Fingerprint=FB:ED:DC:90:65:B7:27:20:37:BC:55:0C:9C:56:DE:BB:F2:78:94:E1 SHA1 /etc/ssl/certs/Certification_Authority_of_WoSign_G2.pem SHA1 Shared/Certificates/FBEDDC9065B7272037BC550C9C56DEBBF27894E1.crt

**Comment by a316323** [comment]
Now, i think what all i can do is just to edit the hosts and add these

127.0.0.1 211.146.10.133
127.0.0.1 wacc.n.shifen.com
127.0.0.1 cstest.cfca.com.cn
127.0.0.1 www.gdca.com.cn
127.0.0.1 cs.cfca.com.cn
127.0.0.1 www.sheca.com
127.0.0.1 root2evtest.wosign.com
127.0.0.1 root1evtest.wosign.com
127.0.0.1 www.startcom.org
127.0.0.1 www.wosign.com
127.0.0.1 root4evtest.wosign.com
127.0.0.1 root5evtest.wosign.com
127.0.0.1 kyfw.12306.cn
127.0.0.1 epki.com.tw
127.0.0.1 www.hongkongpost.hk
127.0.0.1 www.twca.com.tw

**Comment by a316323** [comment]
root@X:/home/X/Downloads/RevokeChinaCerts-master/Linux# ./validator.sh
---------------------
Beginning base tests.
---------------------
? https://wacc.n.shifen.com/
└── wget: (4) failed: Connection refused.
✓ https://211.146.10.133/

1 passing
0 failing
1 skipping
-------------------------
Beginning extended tests.
-------------------------
? https://www.wosign.com/
? https://www.sheca.com/
? https://www.startcom.org/
? https://cs.cfca.com.cn/
? https://root1evtest.wosign.com/
? https://root4evtest.wosign.com/
? https://root2evtest.wosign.com/
└── wget: (4) failed: Connection refused.
└── wget: (4) failed: Connection refused.
? https://root5evtest.wosign.com/
└── wget: (4) failed: Connection refused.
└── wget: (4) failed: Connection refused.
└── wget: (4) failed: Connection refused.
? https://www.gdca.com.cn/
└── wget: (4) failed: Connection refused.
? https://cstest.cfca.com.cn/
└── wget: (4) failed: Connection refused.
└── wget: (4) failed: Connection refused.
└── wget: (4) failed: Connection refused.
└── wget: (4) failed: Connection refused.

0 passing
0 failing
10 skipping
--------------------
Beginning all tests.
--------------------
? https://www.hongkongpost.hk/
? https://kyfw.12306.cn/
? https://www.twca.com.tw/
? https://epki.com.tw/
└── wget: (4) failed: Connection refused.
└── wget: (4) failed: Connection refused.
└── wget: (4) failed: Connection refused.
└── wget: (4) failed: Connection refused.

0 passing
0 failing
4 skipping
-------------------
All tests executed.

**Comment by chengr28** [comment]
Hi, it seems that there are 3 problems:

- `certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.`
   This error message means that `certutil` version is too old and it cannot load the new version of certificate  database, please upgrade `certutil` toolkit of system.
- `Warn! Questionable certificates still exist on your system..`
  This problem has been reported by https://github.com/chengr28/RevokeChinaCerts/issues/91.
- `wget: (4) failed: ..`
  It shows the test after certificate revoking was failed, it looks like a network or test website's problem. You can test them manually to check the certificates are correct revoked or not. For example you can visit https://www.hongkongpost.hk in browser and get security warning if revoking is successful.

**Comment by chengr28** [comment]
It seems that there is another reason about script reporting `certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.`, it's empty database and you should create a new one first. Please visit https://serverfault.com/questions/414578/certutil-function-failed-security-library-bad-database to get more information, thanks.
