### ISSUE TITLE
找不到说明里的四个版本在哪里……

### ISSUE THREAD

**Issue by Demi7** [chengr28/RevokeChinaCerts#110]
批处理/脚本类型

1 为 Base/基础版本：删除信任并吊销了几个可疑的根证书、中级证书或假证书
2 为 Extended/扩展版本：删除信任并吊销了所有可疑的根证书、中级证书或假证书
建议使用此版本
3 为 All/完全版本：删除信任并吊销了所有可疑的来自大中华地区的证书
此版本用于测试不建议使用
4 为 Restore/恢复版本：可恢复所有在上面几个版本中所有被加入吊销列表的证书的使用

**Comment by Demi7** [comment]
Windows 系统证书列表升级

1 为升级 CRL/证书吊销列表
2 为通过 Windows Update 升级 CTL/证书信任列表
3 为通过 RootSUPD 证书更新补丁升级 CTL/证书信任列表（Windows Vista 以前的版本）
4 为重置 CRL/证书吊销列表
要重置对CTL/证书信任列表的更改，需要运行 Microsoft Fixit 工具并重启系统：
Microsoft_Fixit_20135.diagcab - 适用于 Windows Vista 以及更新的版本
Microsoft_Fixit_51014.msi - 适用于 Windows XP/2003 以及以前的版本


↑ 这个东东也找不到……

**Comment by chengr28** [comment]
明明使用方法在版本介绍的前面……就是运行在 `Windows` 目录里的 bat
- Online 是在线版本，就是顶楼的版本
- Firefox 是 Firefox 用的 Online 版本
- CodeSigning 和 Organization 版本是 [Wiki](https://github.com/chengr28/RevokeChinaCerts/wiki/ReadMe_CodeSigning_Organization.zh_Hans) 里介绍的其它用途的版本
- Update 是二楼提到的版本，那几个重置证书配置的工具在 `Windows\Tools\Fixit`
