### ISSUE TITLE
吊销的证书无法恢复

### ISSUE THREAD

**Issue by xiaoneddy** [chengr28/RevokeChinaCerts#111]

**Comment by xiaoneddy** [comment]
![2017-08-18_153105](https://user-images.githubusercontent.com/12034676/29448716-8c855a10-842a-11e7-801e-920e494d007e.png)

**Comment by chengr28** [comment]
使用 Restore 版本可消除列表中证书的吊销状态，不过需要注意是要与吊销时使用的参数相同，例如：
- 是否都（不）为管理员权限运行
- 是否都（不）使用辅助的强制证书规则
- 是否有错误提示输出到屏幕

**Comment by xiaoneddy** [comment]
没有报错，但是很多的网页证书都已经被注销，无法打开证书规则列表里面被拉黑的证书我也使用 Restore版清除掉了，但是还是无法打开被拉黑的证书和安装软件。

**Comment by xiaoneddy** [comment]
已经好了，手动在证书规则里面删除了最后一个不被允许的证书规则。

**Comment by chengr28** [comment]
那还真是奇怪……其实要恢复被吊销的证书，基本上都是先运行各个当初运行过的版本（不同版本之间的证书互相独立，用 A 吊销只能用 A 恢复）的 Restore 模式，然后运行那个 Update 的版本恢复根证书目录的初始状态，不太清楚是什么地方出了问题……

不过之前的确有强制证书规则那个程序运行太快，在 Windows 8 之后的系统导致遗漏的情况，可能需要再观察一下，感谢反馈。
