### ISSUE TITLE
建议添加对思杰马克丁软件证书的过滤

### ISSUE THREAD

**Issue by SadPencil** [chengr28/RevokeChinaCerts#112]
"苏州思杰马克丁软件有限公司"和“苏州小叶网络科技有限公司”是臭名昭著的虚假软件公司（Google之，首页即有大量证据，伪造了很多知名的软件，并占据了百度的搜索结果），建议添加对这些CodeSigning证书的过滤。
![Uploading 2.png…]()

**Comment by SadPencil** [comment]
![2](https://user-images.githubusercontent.com/11227602/29494159-b3266954-85d6-11e7-9915-7f48db186a28.png)

**Comment by Hardrain980** [comment]
According to the Screenshot, 思杰马克丁's Code-signing cert is issued by Wosign, so once Wosign's ROOT CA cert has been revoked, the 思杰马克丁's cert would also be regard as NOT TRUSTED

**Comment by chengr28** [comment]
@Hardrain980 You are right, after check that their certificates are issued by WoSign.
