### ISSUE TITLE
crash问题

### ISSUE THREAD

**Issue by AnnAngela** [chengr28/RevokeChinaCerts#113]
![image](https://user-images.githubusercontent.com/9762652/29742235-bfa7037e-8aad-11e7-807e-d455cadf73c1.png)
运行codesiging那个bat时经常提示文件被锁定以及crash，请问如何是好

**Comment by chengr28** [comment]
之前其实也有人反馈过这类问题，后来发现只有 Windows 8 之后的操作系统会比较高地出现这种现象，可能和 Microsoft 修改了系统证书策略系统的缘故。因为此程序是 Contributor 提供的，这边也不太清楚情况。姑且先当成 bug 下次更新的时候加个等待时间，再看看会不会还会出现文件占用之类的问题。

**Comment by chengr28** [comment]
不好意思，好像时间有点久了，最近才有时间看。这里其实是有两个问题：

* 红色字『系统找不到指定的文件』这个的确是工具的问题，因为 Windows 旧版本非常奇怪地会在证书序列号前添加一个非 ASCII 的字符，导致批处理导入时出问题，一共有 4 个 CodeSigning 的证书有问题，刚才已经修复好了。
* Crash 那个似乎是导入系统证书库的模块 LocalPolicy 的问题，原因如之前说的不明出现，而且经测试似乎 Windows XP 上复现的次数很高。这边做了个异常处理和重试处理，应该不会有 Crash 之类的情况再出现了。

再次表示感谢。
