### ISSUE TITLE
Warn! Questionable certificates still exist on your system.

### ISSUE THREAD

**Issue by moonwater** [chengr28/RevokeChinaCerts#114]
I got some message below, what should I do next?

Warn! We have found hooks in /etc/ca-certificates/update.d
We recommend that you manually check them.

Warn! Questionable certificates still exist on your system.

Please report a bug at:
https://github.com/chengr28/RevokeChinaCerts/issues

Please attach the following output:

Fingerprint=31:F1:FD:68:22:63:20:EE:C6:3B:3F:9D:EA:4A:3E:53:7C:7C:39:17 SHA1 /etc/ssl/certs/StartCom_Certification_Authority_G2.pem SHA1 Shared/Certificates/31F1FD68226320EEC63B3F9DEA4A3E537C7C3917.crt
Fingerprint=3E:2B:F7:F2:03:1B:96:F3:8C:E6:C4:D8:A8:5D:3E:2D:58:47:6A:0F SHA1 /etc/ssl/certs/StartCom_Certification_Authority.pem SHA1 Shared/Certificates/3E2BF7F2031B96F38CE6C4D8A85D3E2D58476A0F.crt
Fingerprint=A3:F1:33:3F:E2:42:BF:CF:C5:D1:4E:8F:39:42:98:40:68:10:D1:A0 SHA1 /etc/ssl/certs/StartCom_Certification_Authority_2.pem SHA1 Shared/Certificates/A3F1333FE242BFCFC5D14E8F394298406810D1A0.crt
Fingerprint=FB:ED:DC:90:65:B7:27:20:37:BC:55:0C:9C:56:DE:BB:F2:78:94:E1 SHA1 /etc/ssl/certs/Certification_Authority_of_WoSign_G2.pem SHA1 Shared/Certificates/FBEDDC9065B7272037BC550C9C56DEBBF27894E1.crt

**Comment by chengr28** [comment]
Please visit https://github.com/chengr28/RevokeChinaCerts/issues/91, thanks.
