### ISSUE TITLE
WoSign OV SSL CA

### ISSUE THREAD

**Issue by qifei** [chengr28/RevokeChinaCerts#115]
路径在 Certum Trusted Network CA 下面

**Comment by chengr28** [comment]
证书 SHA-1 指纹 `FAEE1F690EDD55373C35E491EF0514F3EE9445A5`
之前已被添加到 Extended 版本中，参见 [Wiki](https://github.com/chengr28/RevokeChinaCerts/wiki/ReadMe_Online)
