### ISSUE TITLE
可不可以把 macOS 平台用法翻译一下

### ISSUE THREAD

**Issue by CourierKyn** [chengr28/RevokeChinaCerts#116]
如题

**Comment by chengr28** [comment]
https://github.com/chengr28/RevokeChinaCerts/tree/master/Mac

比起 Linux 平台已经简单很多了吧……好像也没什么难点？

**Comment by CourierKyn** [comment]
那个 import、rebuild 不懂什么意思。。。

发自我的 iPhone

**Comment by chengr28** [comment]
`Rebuild Trust Settings` 意思是重新根据选择（High/Medium/Low）生成 pilst 文件
`Import Trust Settings` 意思是将 plist 的黑名单设置导入系统证书库

**Comment by CourierKyn** [comment]
知道了，谢谢啦

**Comment by CourierKyn** [comment]
还有，merge 和 overwrite 有什么区别？

**Comment by chengr28** [comment]
`Merge` 是在不影响原先系统证书库的情况下将 plist 的规则加入
`Overwrite` 是直接用 plist 的规则覆盖掉系统正在使用的规则
