### ISSUE TITLE
执行 RevokeChinaCerts_Update.bat 失败

### ISSUE THREAD

**Issue by graminc** [chengr28/RevokeChinaCerts#117]
执行 RevokeChinaCerts_Update.bat 失败
CertUtil: 未知参数: -syncWithWU

执行1
RevokeChinaCerts-master\Windows\Certificates\Other 目录下
没有syncWithWU 文件夹

![20171127151415](https://user-images.githubusercontent.com/4575742/33255035-9cb647cc-d386-11e7-9278-38d23bbca20c.png)

执行2

![20171127151922](https://user-images.githubusercontent.com/4575742/33255049-ad6330d0-d386-11e7-8958-7bccee7464ba.png)

**Comment by graminc** [comment]
Windows 7 x64 管理员模式
下载RevokeChinaCerts-master.zip 解压后操作

**Comment by chengr28** [comment]
你这个是什么版本的 Win7 这边 Win7 的 `certutil` 经测试 `-syncWithWU` 参数工作一切正常……有把系统（的功能性）更新到最新吗？

其实这个只是更新系统的证书库，不是强制要求一定要更新的，Vista 之后系统会自动和 Microsoft 服务器核对证书列表，不需要人工干预，不运行也没有大问题。

**Comment by graminc** [comment]
![20171206163335](https://user-images.githubusercontent.com/4575742/33652157-4cbd915c-daa3-11e7-8e93-af0c1e5cd433.png)

64位 补丁通过系统升级 到最新

其实这个只是更新系统的证书库
证书库好像更新了，QQ旋风最新的 版本：4.8.773.400，提示过期了，不能运行了。

没事，谢谢回复。

**Comment by graminc** [comment]
360.cn 官网、苏宁易购(Suning.com) 不能打开了，用的沃通的证书。

**Comment by chengr28** [comment]
关于这几个问题：
* 软件提示过期说明是软件自己的证书有问题或者被吊销，因为软件一般都有时间戳签名，不会受时限影响的，而且 Vista 之后的系统根证书实际上是实时和 Microsoft 同步的，不需要用户干预。
* WoSign 的证书在列表里很长时间了……
