### ISSUE TITLE
360 安装程序签名证书需要 增加/更新 证书来拦截

### ISSUE THREAD

**Issue by graminc** [chengr28/RevokeChinaCerts#118]
360 安装程序签名证书需要 增加/更新 证书来拦截

![20180105005632](https://user-images.githubusercontent.com/4575742/34574870-b65a2d56-f1b3-11e7-8900-a92f601c8cb3.png)

setup_bd 360安全卫士 11.4.0.2049 百度软件中心下载

![20180105005649](https://user-images.githubusercontent.com/4575742/34574863-b1d5bfde-f1b3-11e7-8bce-9f6461ff61db.png)

 
![20180105010540](https://user-images.githubusercontent.com/4575742/34575142-9ec81d50-f1b4-11e7-9eb5-144010030725.png)

证书目前有效期截止到19年3月29日

**Comment by graminc** [comment]
https://www.360.cn/

360首页hhtps 目前拦截倒是正常

**Comment by chengr28** [comment]
似乎是混淆了在线证书和代码签名证书的区别：
* 网站的证书属于前者，由于其使用 WoSign 的证书，所以可以被 [Online](https://github.com/chengr28/RevokeChinaCerts/wiki/ReadMe_Online) 版本吊销。
* 截图那个软件的证书属于后者，可以被 [CodeSigning](https://github.com/chengr28/RevokeChinaCerts/wiki/ReadMe_CodeSigning_Organization) 版本吊销，实际上这个证书也已经在列表上了。

**Comment by graminc** [comment]
我在 https://github.com/chengr28/RevokeChinaCerts ，通过 clone or download、download Zip
下载RevokeChinaCerts-master.zip ，解压后Windows 文件夹下 
RevokeChinaCerts_CodeSigning.bat                                 
RevokeChinaCerts_Online.bat  
RevokeChinaCerts_Organization.bat
三个bat文件

与在页面
https://github.com/chengr28/RevokeChinaCerts/blob/master/Windows/RevokeChinaCerts_CodeSigning.bat
https://github.com/chengr28/RevokeChinaCerts/blob/master/Windows/RevokeChinaCerts_Online.bat
https://github.com/chengr28/RevokeChinaCerts/blob/master/Windows/RevokeChinaCerts_Organization.bat

raw按钮右键另存为下载的三个bat文件哈希校验不同，不知道内容有何区别？

**Comment by graminc** [comment]
以哪个为准呢？
11月份下载过 RevokeChinaCerts-master.zip
RevokeChinaCerts_CodeSigning.bat
RevokeChinaCerts_Online.bat
RevokeChinaCerts_Organization.bat
三个bat文件也都执行过

**Comment by graminc** [comment]
![20180106143641](https://user-images.githubusercontent.com/4575742/34637391-9581dcd0-f2f0-11e7-8bd8-83e333b640bc.png)
原有排除的不信任证书
证书目前有效期截止到16年3月11日，有效期好像从13年开始。

现在
颁发者使用者都没变
VeriSign Class 3 Code Signing 2010 CA
Qihoo 360 Software (Beijing) Company Limited 

证书目前有效期截止到19年3月29日，从16年开始的。
签名证书换了或者说更新了。

![20180106145722](https://user-images.githubusercontent.com/4575742/34637436-f2f07cea-f2f1-11e7-8b08-09bebabe67bc.png)

**Comment by graminc** [comment]
Tencent Technology(Shenzhen) Company Limited
不就有三个吗？三个截止日期不同而已。

![20180106150017](https://user-images.githubusercontent.com/4575742/34637473-8e8d0416-f2f2-11e7-9bc8-b9b3206f8566.png)

**Comment by chengr28** [comment]
bat 的 Hash 不相同是正常的……页面 raw 下载回去的是 LF 换行符的文件，通过 Download ZIP 方法下回去因为这边有配置文件，所以生成的时候会使用 CR + LF 换行符，相同才是不正常……内容应该是一模一样的。

**Comment by chengr28** [comment]
以现在在 GitHub 上的版本为准，具体不太清楚是什么时候加入的了，不过实际上应该是添加了一段时间的了。数字的证书在 [CodeSigning](https://github.com/chengr28/RevokeChinaCerts/wiki/ReadMe_CodeSigning_Organization) 查过都是有的，就是 2019-03-29 过期的，指纹如下：

> D4FB2982268B592E3CD46FA78194E71418297741
> 978859CE5698F2BFADE1129401CF70856BE738D3

**Comment by chengr28** [comment]
如果还有问题可以直接在这里回复。
