### ISSUE TITLE
这么多证书是怎么导出来的

### ISSUE THREAD

**Issue by sharoue** [chengr28/RevokeChinaCerts#120]
这么多证书，作者有从exe文件批量导出证书的工具吗？目前我只能右键一个个来，十分痛苦。
因为工作原因，我需要屏蔽更多的正常软件，同时部分在项目的证书不能屏蔽。如果有工具的话，有利于自己建立一个证书黑名单……

**Comment by chengr28** [comment]
关于证书导出，这边并没有找到这样的工具，因为签名是附带在 exe 中的，都是从 Windows 自带的属性浏览器才能看到。不过一般来说这种证书有效期都是几年，不常更新，添加起来也不是很麻烦……
