### ISSUE TITLE
Revoke之后无法安装Python3.6.4

### ISSUE THREAD

**Issue by emowen** [chengr28/RevokeChinaCerts#123]
安装包是从[Python](python.org)官网上下载的

**Comment by chengr28** [comment]
Python 的安装包是用 StartCom 的证书签名的，被吊销了自然就装不了了……

**Comment by KrasnayaPloshchad** [comment]
建议给他们反馈，途径在此：https://www.python.org/community/

**Comment by chengr28** [comment]
StartCom 都倒闭了……看了他们证书大约 2019 年 2 月份会过期，应该之前就会换掉。
