### ISSUE TITLE
Mac上使用 strict 模式导入, Test Trust Setting 依旧有6个失败

### ISSUE THREAD

**Issue by evecalm** [chengr28/RevokeChinaCerts#126]
如下图, 我使用的是 macOS 10.13.4 (17E202)

![image](https://user-images.githubusercontent.com/1655294/39734665-e64a3a3a-52aa-11e8-8872-0869b02dbc27.png)

**Comment by chengr28** [comment]
其实按照个人的理解，那个 `Rebuild Trust Settings` 是生成证书数据库，而 `Import Trust Settings` 是导入证书数据库到系统中，所以 `MODE=strict ./build-trust-settings.sh` 之后还要再 `./import-trust-settings.sh`。

**Comment by chengr28** [comment]
1. sheca 那个换成 GlobalSign 的证书，之前的更新已经去掉了
2. WoSign 无法阻止访问原因不明，推测水果策略有问题，和之前 NSS 遇到的问题应该是一样的，参见 https://github.com/chengr28/RevokeChinaCerts/issues/91
3. gdca 那个应该是后来 Certum 签的中级证书，之后更新会添加，感谢反馈

**Comment by chengr28** [comment]
GDCA 的中级证书是 Certum CA 而不是他们自己的 CA 签的，所以连同之前找到的另外 2 个，刚才的更新已经添加进去了，感谢反馈。

**Comment by evecalm** [comment]
刚刚更新试了一下, gdca的还是可以访问, 但是查看其网站证书, 和沃通的网站一样, 中级证书都显示不信任. 苹果证书管理策略是有点诡异.

![image](https://user-images.githubusercontent.com/1655294/40270346-372d1b18-5bbe-11e8-85d8-d693c7a2291f.png)
