### ISSUE TITLE
将 .bat 脚本均改写为 .ahk 脚本后编译为 .exe，用户体验会好得多。

### ISSUE THREAD

**Issue by szzhiyang** [chengr28/RevokeChinaCerts#127]
我对 .bat 脚本和 .ahk 脚本都很熟悉，这些 .bat 脚本被改写为 .ahk 脚本后可以随同证书文件和 Certmgr.exe 一起编译为一个单独的带 GUI 的 .exe 单文件，并且可以自动弹 UAC，用户体验会好得多。

需要我帮忙吗？

**Comment by wongsyrone** [comment]
咦？autohotkey脚本吗。以前我也写过，不过编译之后容易被报毒

**Comment by szzhiyang** [comment]
@wongsyrone 

很多人似乎对复杂的文件结构以及几个不同功能的 .bat 批处理感到无所适从，将这些东西打包到一起再用 AutoHotkey 做个简单的界面对于使用者来说是最友好的。

**Comment by wongsyrone** [comment]
我感觉用批处理可以直接运行并方便修改，改成其他的需要先编译再用，可能基于这样的考虑才没有使用其他脚本来做吧。

**Comment by szzhiyang** [comment]
@wongsyrone 

我以前就很喜欢写批处理，但是当我学会 AutoHotkey 以后就再也没有写过了，因为 AutoHotkey 的优点实在是太明显了。它语法跟批处理一样简单，却能做 GUI 以及很多很多批处理根本做不到的事情。

**Comment by szzhiyang** [comment]
@chengr28 

我跟你合作行吗？其实真的不难的。

**Comment by chengr28** [comment]
这个并不是合作的问题，任何对项目的建议和意见都是可以的。

就事论事，关于这个项目到底需不需要一个集成的 GUI 的问题。就像你说版本多是『无所适从』实际上相关的说明都有，如果按照本 issue 的建议，将全部功能集成到一个 exe 里，的确是很傻瓜式了。问题是，是不是所有人听说某某证书有危险，就马上下个 exe 然后无脑双击运行万事大吉？我不希望项目向这种方向发展。决定在自己的机器上运行某个程序之前，最起码要知道事情的来龙去脉，目的是什么，为什么会需要管理员权限，使用后会有什么后果吧？就算打包成了 GUI 上面如果不摆（可能一大堆的）说明，那还是一样不清不楚，那和现在用批处理有什么区别？

正如前面讨论所说，虽然 GUI 可以实现更高级的功能，但本来本项目就像是胶水，将不同的现成的工具粘合起来，批处理可以直接运行并方便修改，当然就是首选了……尤其是项目设计就是用于自动化工作的，需要人工干预的部分越少越好，最近的更新还添加了参数进行自动控制。
