### ISSUE TITLE
是否有计划加入特供版flash

### ISSUE THREAD

**Issue by muink** [chengr28/RevokeChinaCerts#129]
已经被淘汰的东西还来恶心一波

:page_facing_up: [Helper Service 最终用户协议](https://www.flash.cn/Helper_Service_Agreement.pdf)  

> ![0](https://user-images.githubusercontent.com/7929014/41911274-c96ea6b2-797e-11e8-8adf-a421bb3fd873.PNG "静默安装")  
![1](https://user-images.githubusercontent.com/7929014/41911281-cf23aa30-797e-11e8-9d87-979152957469.PNG "收集用户信息")  
![2](https://user-images.githubusercontent.com/7929014/41911287-d57f68ec-797e-11e8-8387-947dcbb86f4e.PNG "收集到的信息可与第三方公司共享且没有任何保证，也没有对「合理范围」的定性")  
![3](https://user-images.githubusercontent.com/7929014/41911299-dcbdacfe-797e-11e8-8fd3-59b811c0bc15.PNG "并且以此导致的后果无需负责任")  
![4](https://user-images.githubusercontent.com/7929014/41911313-e29d05e8-797e-11e8-8e96-330cb1a6ac0a.PNG "协议更改无需最终用户再次确认")

简直赤果果的霸王协议

### 相关

[如何看待Adobe Flash Player锁区？](https://www.zhihu.com/question/281163698)  
[如何评价 Adobe Flash Player 捆绑2144游戏中心？](https://www.zhihu.com/question/50781142/answer/412437630)  
[Adobe Flash开始捆绑2144游戏中心](https://www.solidot.org/story?sid=49727)  
[Aodbe Flash 怎么也玩弹窗这一手了？](https://www.v2ex.com/t/465361)

**Comment by KrasnayaPloshchad** [comment]
地址：https://www.flash.cn/

**Comment by chengr28** [comment]
已经将 FlashHelperService 和安装程序捆绑的 2144 的证书添加到 CodeSigning 列表中，感谢反馈。
