### ISSUE TITLE
GDCA 存在什么问题？

### ISSUE THREAD

**Issue by wbsdty331** [chengr28/RevokeChinaCerts#130]
RT，看了一下`ReadMe_Online.md`，然后仔细回想了一下， GDCA（也就是数安时代）好像就是签发了几个 1024-Bit 的证书

**Comment by chengr28** [comment]
总结起来就是被广泛内置成 CA 的天朝证书颁发机构。

**Comment by wbsdty331** [comment]
我认为应该坚持「疑罪从无」原则：在 GDCA **没有做出恶意行为**（肆意签发证或 MITM）之前，应该从列表中暂时移除，这是 RevokeChinaCerts，不是 RevokeAllChinaCerts。

**Comment by chengr28** [comment]
那你不应该使用本项目。
