### ISSUE TITLE
Not working on Win 10

### ISSUE THREAD

**Issue by kmahyyg** [chengr28/RevokeChinaCerts#131]
Running Win10 2016 LTSB 14393 Build from MSDN
Run the script with administrator privileges.
All messages showed on the screen seems successfully executed the operation.

However, the distrusted cert is still empty. 
In secpol.msc , the software restriction rules (additional rules tab) is also empty.

BTW, some certs are expired, you may need to update these code-signing certs until they were valid.

Further information could be provided.

**Comment by chengr28** [comment]
Thanks for your report, SoftCertPolicyAppender has a bug which opposites operation. Please get the latest version and restore/revoke again. Please notice that only CodeSigning/Organization will add certificates to software restriction list.

Also about the expired certificates, there are two points:
1. Timestamp, please read https://stackoverflow.com/questions/4417410/why-should-we-set-a-timestamp-when-we-do-a-codesigning.
2. User can ignore verificating error even certificate is expired, so we need to revoke certificate to prohibit this operation.
