### ISSUE TITLE
Cert not found while revoking

### ISSUE THREAD

**Issue by kmahyyg** [chengr28/RevokeChinaCerts#132]
Windows, Organization Patch

```cmd
1.Add certificate policy for CN=WoSign EV Code Signing Pro CA, O=WoSign CA Limited, C=CN(3CE2118D75A2258C53A3D7A26512160E09AA0FE9)
Done
Apply force certificate policy.
System.Security.Cryptography.CryptographicException: The system cannot find the file specified.

   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.X509Certificates.X509Utils._QueryCertFileType(String fileName)
   at System.Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromFile(String fileName, Object password, X509KeyStorageFlags keyStorageFlags)
   at SoftCertPolicyAppender.Program.Main(String[] args)
The system cannot find the file specified.
Please select: Retry, Ignore or Abort (R|I|A)
```

**Comment by chengr28** [comment]
I cannot find the reason which make this case, it seems it will get the same error even retrying more. Different certificate will get the same error in different machine, but there are no any errors in some machines. Also certificate files are normal..

**Comment by chengr28** [comment]
Maybe you can try the new version, which fixs file extension error in CodeSigning by https://github.com/chengr28/RevokeChinaCerts/issues/134.

**Comment by chengr28** [comment]
OK, after reviewing https://github.com/chengr28/RevokeChinaCerts/issues/134 , found that:
```
Apply force certificate policy.
1.Add certificate policy for CN=WoSign EV Code Signing Pro CA, O=WoSign CA Limited, C=CN(3CE2118D75A2258C53A3D7A26512160E09AA0FE9)
Done
```
is process of 3CE2118D75A2258C53A3D7A26512160E09AA0FE9. Then the next step
```
Apply force certificate policy.
System.Security.Cryptography.CryptographicException: The system cannot find the file specified.
...
```
is process of 3E2508B896541F186A7B4AC6925F0ADDCC3677F2. The second process was failed because of file file extension mismatch. Thanks for your report again.
