### ISSUE TITLE
自动化流程处理扩展名问题

### ISSUE THREAD

**Issue by muink** [chengr28/RevokeChinaCerts#134]
`3E2508B896541F186A7B4AC6925F0ADDCC3677F2.cer`这个证书用的不是crt后缀
代码签名批处理在处理的时候按统统`*.crt`通配符处理导致在执行时遇到问题

![image](https://user-images.githubusercontent.com/7929014/43253961-d73e1282-90f8-11e8-80b6-823f0b941935.png)

**Comment by wongsyrone** [comment]
Similar to https://github.com/chengr28/RevokeChinaCerts/issues/132

**Comment by chengr28** [comment]
好吧 `3E2508B896541F186A7B4AC6925F0ADDCC3677F2.cer` 这个扩展名的确是有问题的……一会儿更新一下。

**Comment by chengr28** [comment]
@wongsyrone https://github.com/chengr28/RevokeChinaCerts/issues/132 这个问题应该不是这个，因为那里也有说不同环境上出现问题的证书似乎都不一样，当然也不排除是这个 `cer` 导致的连锁反应，或者先更新一下再看看情况。

**Comment by chengr28** [comment]
改好了，感谢反馈。

**Comment by chengr28** [comment]
@wongsyrone 好吧，重新 review 了最近的 issue 发现 https://github.com/chengr28/RevokeChinaCerts/issues/132 的确就是这个 issue 提到的问题造成的。一开始
```
3CE2118D75A2258C53A3D7A26512160E09AA0FE9
```
的处理是没有问题的，然后再下面从 `Done` 后面开始是另外一个
```
3E2508B896541F186A7B4AC6925F0ADDCC3677F2
```
的处理过程，这个因为扩展名的问题所以有出错，当时第一次判断的时候应该是把两个不同的证书过程搞混了……可能后期还要多加一点分隔或者标识之类。
