### ISSUE TITLE
...

### ISSUE THREAD

**Issue by imlibra** [chengr28/RevokeChinaCerts#135]
刚才看到一个波兰的CA给GDCA发了一个中级证书，我觉得应该考虑把C=PL C=HU C=TK的这些名都不写英文的证书拉进黑名单。
我记得还有几个委内瑞拉 C=VE的，显然更危险。

**Comment by imlibra** [comment]
那个中级证书

`-----BEGIN CERTIFICATE-----
MIIEzzCCA7egAwIBAgIRANX4Po3a9nyIKeiQFreHfRMwDQYJKoZIhvcNAQELBQAw
gYMxCzAJBgNVBAYTAlBMMSIwIAYDVQQKExlVbml6ZXRvIFRlY2hub2xvZ2llcyBT
LkEuMScwJQYDVQQLEx5DZXJ0dW0gQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxJzAl
BgNVBAMTHkNlcnR1bSBHbG9iYWwgU2VydmljZXMgQ0EgU0hBMjAeFw0xODAxMjYw
OTIxNThaFw0yNzA1MjAwOTIxNThaMHExCzAJBgNVBAYTAkNOMTkwNwYDVQQKDDBH
bG9iYWwgRGlnaXRhbCBDeWJlcnNlY3VyaXR5IEF1dGhvcml0eSBDby4sIEx0ZC4x
JzAlBgNVBAMMHkdEQ0EgVHJ1c3RBVVRIIFI0IEVWIFNTTCBDQSBHMjCCASIwDQYJ
KoZIhvcNAQEBBQADggEPADCCAQoCggEBALNPfXyROlIMdwEmVT0Nu3eQlWj6+Hty
73vWjqUWUVOfWdGFWstQ8jvy6unc1G6b81v1+er9viceJLhVttPBxQ5l4ekWO+wT
kATYKDRM1e529qFI+rEjOwCQz7lwYA7nLXhfpv6ml068tSarpgr+sLyY8UyhUT4q
jtSRfR7U4Uq3afGgCFzDirPJI/0GjvBo1v9fqtyvBwAl5LddhmN0T5u2ufTRs3tN
IAxcWFyWe618/s+ZNA5DTNo+onBJTZ1Dxb/a90moZzyfP7niQ2Q//2s+f4DlNDQ4
moI0M/xg5vwQQ/CKW5ofxB86TDrNrvcHvo8yieWN1uTp/SvEnbEvXBkCAwEAAaOC
AU0wggFJMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFLNjEYy6JTesOKDc
N0TrbQ49PMiLMB8GA1UdIwQYMBaAFFSZ3Zv/6KcOoxmdW75CV98w/I8yMA4GA1Ud
DwEB/wQEAwIBBjA4BgNVHR8EMTAvMC2gK6AphidodHRwOi8vc3ViY2EuY3JsLmNl
cnR1bS5wbC9nc2Nhc2hhMi5jcmwwbgYIKwYBBQUHAQEEYjBgMCgGCCsGAQUFBzAB
hhxodHRwOi8vc3ViY2Eub2NzcC1jZXJ0dW0uY29tMDQGCCsGAQUFBzAChihodHRw
Oi8vcmVwb3NpdG9yeS5jZXJ0dW0ucGwvZ3NjYXNoYTIuY2VyMDkGA1UdIAQyMDAw
LgYEVR0gADAmMCQGCCsGAQUFBwIBFhhodHRwOi8vd3d3LmNlcnR1bS5wbC9DUFMw
DQYJKoZIhvcNAQELBQADggEBAISNtyVOURlXscYXg5hahYysadf0abiUpMmREnu5
rYx4asAdLMncnVyUGFgfn/2cQXoZROnWGcYmvtEJbLaAK9k/CcZZFLC+JTJpdLw1
lxW0KFCqhEl6O1vu0YkzCaTpKw+9jm+AJvsxBHIJgk3v1h+aO7eAskM+PWjIMI86
6M5wM7CAESLJ8E+gps9jX3uYeb/9O3HLTUucvgBxAxiRNu/FloX3bbc1VmB6q1pH
wntPTTyqntFt30Kss0b2veA0JcPF0YMXotRYYeFRf9KeY629IBN/f30uYfN8XmaG
nM7ukUvdQSMgrLQYuRR+FA20Z9DRqMl2IBo51/ddvYFHbAo=
-----END CERTIFICATE-----`

**Comment by imlibra** [comment]
现在的网络临侦设备标准已经要求可以侦听https连接，不弹出可疑证书提示
[http://www.greytech.org/productSolution.html](url)
<img width="1078" alt="2018-10-19 5 48 48" src="https://user-images.githubusercontent.com/33746337/47211124-4be43600-d3c7-11e8-8517-ba2215364a6f.png">

**Comment by chengr28** [comment]
这个证书已经有了：87DFE0056D01EB9635395D44A856218484F492F0
