### ISSUE TITLE
追加上海滩 ECA

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [chengr28/RevokeChinaCerts#140]
参阅博文：https://blog.wongcw.com/2019/02/09/sheca%E6%A0%B9%E8%AD%89%E6%9B%B8%E5%B7%B2%E7%B6%93%E8%A2%AB%E7%B4%8D%E5%85%A5mozilla%E8%AD%89%E6%9B%B8%E5%BA%AB/

**Comment by chengr28** [comment]
https://github.com/chengr28/RevokeChinaCerts/blob/master/Shared/Documents/ReadMe_Online.md
这 2 个根证书之前就已经包含了。
