### ISSUE TITLE
作者对最近的Epic Game窃取资料事件怎么看

### ISSUE THREAD

**Issue by muink** [chengr28/RevokeChinaCerts#141]
https://www.youtube.com/watch?v=zcIPJG7HUaM

https://www.reddit.com/r/PhoenixPoint/comments/b0rxdq/

看了一下国外的讨论贴，除了偷steam的用户数据
还有枚举用户进程，操作读取系统证书的行为
不知作者怎么看

**Comment by chengr28** [comment]
V 社说正在调查，不过偷偷摸摸的行为见惯不怪，毕竟大股东是 Te..
