### ISSUE TITLE
请考虑更新证书

### ISSUE THREAD

**Issue by Prurite** [chengr28/RevokeChinaCerts#142]
我在运行 RevokeChinaCerts_CodeSigning.bat 和 RevokeChinaCerts_Online.bat 后进入 certmgr.msc 中看了一下，许多被拉黑的证书本身已经过期，这些企业已经有了新的证书，请考虑更新应吊销证书的列表。

**Comment by chengr28** [comment]
新的证书有空可以更新一下，至于过期的证书不能移除，因为对二进制可执行文件的签名有 timestamp 如果以前（包括过期）的证书没有吊销的话，旧版本的二进制可执行文件是可以运行的。

**Comment by chengr28** [comment]
已更新，感谢反馈。
