### ISSUE TITLE
多了几个根证书，望周知

### ISSUE THREAD

**Issue by zmz125000** [chengr28/RevokeChinaCerts#143]
Certificate "emSign Root CA - G1"
Issuer: CN=emSign Root CA - G1,O=eMudhra Technologies Limited,OU=emSign PKI,C=IN
Fingerprint (SHA1): 8A:C7:AD:8F:73:AC:4E:C1:B5:75:4D:A5:40:F4:FC:CF:7C:B5:8E:8C

Certificate "emSign ECC Root CA - G3"
Issuer: CN=emSign ECC Root CA - G3,O=eMudhra Technologies Limited,OU=emSign PKI,C=IN
Fingerprint (SHA1): 30:43:FA:4F:F2:57:DC:A0:C3:80:EE:2E:58:EA:78:B2:3F:E6:BB:C1

Certificate "emSign Root CA - C1"
Issuer: CN=emSign Root CA - C1,O=eMudhra Inc,OU=emSign PKI,C=US
Fingerprint (SHA1): E7:2E:F1:DF:FC:B2:09:28:CF:5D:D4:D5:67:37:B1:51:CB:86:4F:01

Certificate "emSign ECC Root CA - C3"
Issuer: CN=emSign ECC Root CA - C3,O=eMudhra Inc,OU=emSign PKI,C=US
Fingerprint (SHA1): B6:AF:43:C2:9B:81:53:7D:F6:EF:6B:C3:1F:1F:60:15:0C:EE:48:66

Certificate "Hongkong Post Root CA 3"
Issuer: CN=Hongkong Post Root CA 3,O=Hongkong Post,L=Hong Kong,ST=Hong Kong,C=HK
Fingerprint (SHA1): 58:A2:D0:EC:20:52:81:5B:C1:F3:F8:64:02:24:4E:C2:8E:02:4B:02
https://www.v2ex.com/t/563772

**Comment by chengr28** [comment]
最后那个 CA 已经添加到 All 列表里了，至于 emSign 是有什么问题吗？

**Comment by zmz125000** [comment]
没有了
