### ISSUE TITLE
我这里导出了几个二级证书，麻烦也加一下

### ISSUE THREAD

**Issue by zhanhb** [chengr28/RevokeChinaCerts#145]
-----BEGIN CERTIFICATE-----
MIIFozCCA4ugAwIBAgIQOW5mXkXjp5e2l/z+MQ2S7jANBgkqhkiG9w0BAQsFADBV
MQswCQYDVQQGEwJDTjEaMBgGA1UEChMRV29TaWduIENBIExpbWl0ZWQxKjAoBgNV
BAMTIUNlcnRpZmljYXRpb24gQXV0aG9yaXR5IG9mIFdvU2lnbjAeFw0xNDExMDgw
MDU4NThaFw0yOTExMDgwMDU4NThaMFIxCzAJBgNVBAYTAkNOMRowGAYDVQQKExFX
b1NpZ24gQ0EgTGltaXRlZDEnMCUGA1UEAxMeV29TaWduIENsYXNzIDEgRFYgU2Vy
dmVyIENBIEcyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuP82QaTQ
KXvX3KppHmSFAMbUO+FiC5eQifBLLFrJKyLeorXSwNWO05JA947nmX+ryKL03inu
EdEWwrbPFHkNVChaOPuM2QAUuX+0Wx40FNl0Gr/ykvEF+WkS3QGDkO5YkwS0qWbM
yBAlCetSNTMUJOJnIDr4qIe2z33UWNl6dFmOWE+ML8mR+SIiM0ezwabR9OaKq3IC
6v15FnQyBSuLs5p+CCmPqyBRhD5qEIaxmqOtjU4A7/ZCU9i9q7lJN5U5OBCRMsuw
XTp/VImfj+6/VvtcUpiS4KGEOyihYju/PSFPOTI2ujGXw6cnhwW10THPmUCCeYoh
QfTBf2zMhx2adwIDAQABo4IBcDCCAWwwDgYDVR0PAQH/BAQDAgEGMB0GA1UdJQQW
MBQGCCsGAQUFBwMCBggrBgEFBQcDATASBgNVHRMBAf8ECDAGAQH/AgEAMDAGA1Ud
HwQpMCcwJaAjoCGGH2h0dHA6Ly9jcmxzMS53b3NpZ24uY29tL2NhMS5jcmwwbQYI
KwYBBQUHAQEEYTBfMCcGCCsGAQUFBzABhhtodHRwOi8vb2NzcDEud29zaWduLmNv
bS9jYTEwNAYIKwYBBQUHMAKGKGh0dHA6Ly9haWExLndvc2lnbi5jb20vY2ExZzIt
c2VydmVyMS5jZXIwHQYDVR0OBBYEFCVj1cFjzeZB4+9lcMETuo0jdIvxMB8GA1Ud
IwQYMBaAFOFmzw7R8bNLtwYgFP6HEtX2/vs+MEYGA1UdIAQ/MD0wOwYMKwYBBAGC
m1EGAQIBMCswKQYIKwYBBQUHAgEWHWh0dHA6Ly93d3cud29zaWduLmNvbS9wb2xp
Y3kvMA0GCSqGSIb3DQEBCwUAA4ICAQARS3UCfDXiC2ixcpYZsDezmfpAL4G80MrN
N4CUYxSlV7icc3rNqGG1tc0THG/PBRPzALWFRJblkcZAaTRugi+HDbo2+Wq8ngoF
gd1zGgxprI/EAz2s+wWZUXlZgQ0p4FOC1jdiIna/CKyKliD5LklgPR8ikQS93yE0
A6rnd2Lnt+0XtybOPLxEJzB04gDQUzPNPnhaameUXkwCSRxBP3xqC8z9+9LAvtGv
TNLQ1G6pVbQMmecftvWvqCs1WPts0O0hBZaW9ouIRRfUiK0hbVOC98yhXPJlMbTB
L3VlnZn3PUdrl6tPb4pQjrLFZLuqcZ8b2TrL8IxXPZwG61qc5KRrmwxHnAjqxnnO
20y0Tis9GYVuDaINrVfkJMhV/K2Ogk12dzOWL4tY2R9mOyVRKMN1OhhZFsO9zqQe
O2suDDgReKX/QnXmuCf75UbVG5CrqIORKTgv0Y2OewYFNl4zqnVZ/o6v9/XF0O2i
j/eOrubc0g1Yh67LR6ctJUFw1uW+3TSOBqNFPH2HtMfORtoC5Jn0PR7ZbjuCftBV
p/Ed6yPB6pJjlEevBL9jTVP7OkMLPBXO7t+8/UTdP2kM9pIBcpoH/KTx2kvHIp8e
z4UpWMiVDwTdFqEPtyEbF4dKsSz6/w9wYrOEW/b7rdgtFpFqkkoZFgNI4PeJxcsK
Ah9qz1oHfg==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIEiTCCA3GgAwIBAgIQC3+VkOWE0G8LcWoF7Z/i/DANBgkqhkiG9w0BAQsFADBs
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSswKQYDVQQDEyJEaWdpQ2VydCBIaWdoIEFzc3VyYW5j
ZSBFViBSb290IENBMB4XDTE3MDUyMzEyMDQwN1oXDTI3MDUyMzEyMDQwN1owSDEL
MAkGA1UEBhMCQ04xGjAYBgNVBAoTEVdvU2lnbiBDQSBMaW1pdGVkMR0wGwYDVQQD
ExRXb1NpZ24gRVYgU1NMIFBybyBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBANmDz1NN4EL1KzW0T6fOkR7IQSXAc28dqEHAJs67wM5LnI71rGWHJ4dY
FvDW4RaQMwNq5Q7r6s6TIM+iH+dTPs6qFiEO8HqbrgVD0zHBfqtzhNUt2OTnNfe4
npAH6U1zX+Oi6736U0CLawu6mz5BUGcH+0FoOe4suB9DTB/tZpmjPkg+2Cr7pmTG
dBVhd4jG0a+kM79wykUvr08IOWBB25nUGc/12fLM7B3oItKZ3vaPuEnlGvA0Kp2u
W+NcayG6wmJDA4FXQdWBnStKXJFvJsXu22mGKcLsxWYNTZcsa2Z/rOSRdVb1SJ3G
wWqWcHDNmil9ySZohNXpAov0IFutpJ8CAwEAAaOCAUkwggFFMB0GA1UdDgQWBBSu
D77DDWUUIl3SUSi2oAyMWfTjGzAfBgNVHSMEGDAWgBSxPsNpA/i/RwHUmCYaCALv
Y2QrwzAOBgNVHQ8BAf8EBAMCAYYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUF
BwMCMBIGA1UdEwEB/wQIMAYBAf8CAQAwNAYIKwYBBQUHAQEEKDAmMCQGCCsGAQUF
BzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wSwYDVR0fBEQwQjBAoD6gPIY6
aHR0cDovL2NybDQuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0SGlnaEFzc3VyYW5jZUVW
Um9vdENBLmNybDA9BgNVHSAENjA0MDIGBFUdIAAwKjAoBggrBgEFBQcCARYcaHR0
cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzANBgkqhkiG9w0BAQsFAAOCAQEApREf
v9/3Dv4T70+xHfRWXxF7VautSJxPNVUhr/vuvqRqQVXJs8WZ0eJWk01kiM7yfzrn
BV1EMsc9E26A95X9/LzA+5xQfVD7Wh+Ww/ErE1mW5AEBu+ElYtrtyTKStTi+RUEB
DzJ6q8PySaJpi6xad1LCBmribNvVK1t45lCPj2fnOVPybmWsblDR6WQmpFBuYIBi
EwDHbqXbXRF/XiSeJLIU8FtqsPu+wGAefviaIoa+EAw34QF9oD5xQUznoIrZEJxC
lE+nP+7K2GhtKQtSK5EdiopZy6xsERubQVabApgm1CVdrEl8IGdUlvheooz6I5/F
9xYIvypgbmpLkt8IOw==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIFJzCCBA+gAwIBAgIQBrytuehQBysrKDIQVF8fGzANBgkqhkiG9w0BAQsFADBs
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSswKQYDVQQDEyJEaWdpQ2VydCBIaWdoIEFzc3VyYW5j
ZSBFViBSb290IENBMB4XDTE4MDIwOTEyMzIyM1oXDTI4MDIwOTEyMzIyM1owSDEL
MAkGA1UEBhMCQ04xGjAYBgNVBAoTEVdvVHJ1cyBDQSBMaW1pdGVkMR0wGwYDVQQD
ExRXb1RydXMgRVYgU1NMIFBybyBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBALNu+EJh4IFRwb+NSkUA2PuSgGBJX7Dv0WHF1UnHGTaxvNrKypQ2Y4YM
8UWBN6GtERHYnVPFREbMZm7rH57JfSqCRQh/fnZIW8YKQKye3LTQ9RDCe1tqUnr7
q4dPHGhtJPc0ysDZOhxdvxf6bkDZWpejXwzDIVyPG89tGEgl6eISrg96MOOUDcln
762bSBVzozcYRrCiaPWipEzo+38LbqnDhSDPAH1AnkTofeTJ+K45xVja4kovzOKh
EaSNL79fUMsfN0A57Xdgoykl8EnoG5qFk2mSCGruZVRhvU3p9/hlI3s5yvnS32k+
9Dun/Ns/lTmoOsZiGVw1e2/F3eAHweECAwEAAaOCAecwggHjMB0GA1UdDgQWBBTW
kdAnx/cYVmiiUv1ydKSbO2eUyTAfBgNVHSMEGDAWgBSxPsNpA/i/RwHUmCYaCALv
Y2QrwzAOBgNVHQ8BAf8EBAMCAYYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUF
BwMCMBIGA1UdEwEB/wQIMAYBAf8CAQAwfwYIKwYBBQUHAQEEczBxMCQGCCsGAQUF
BzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wSQYIKwYBBQUHMAKGPWh0dHA6
Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEhpZ2hBc3N1cmFuY2VFVlJv
b3RDQS5jcnQwgY8GA1UdHwSBhzCBhDBAoD6gPIY6aHR0cDovL2NybDMuZGlnaWNl
cnQuY29tL0RpZ2lDZXJ0SGlnaEFzc3VyYW5jZUVWUm9vdENBLmNybDBAoD6gPIY6
aHR0cDovL2NybDQuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0SGlnaEFzc3VyYW5jZUVW
Um9vdENBLmNybDBLBgNVHSAERDBCMDcGCWCGSAGG/WwCATAqMCgGCCsGAQUFBwIB
FhxodHRwczovL3d3dy5kaWdpY2VydC5jb20vQ1BTMAcGBWeBDAEBMA0GCSqGSIb3
DQEBCwUAA4IBAQC9xqN5M4SnTGzIEl2GKm7+3OLikAmlts8dinuT5KndrKq9sygQ
T6MYUR1Giwd7jUl9zq5X8edd2z/p41GqWkWhKpMiqImqB9iua7MPmQKGMd/9czDU
d4wIBpBUQVNWK+VXLxRuk7iDIKkSIUThDwijFRUjEsBEsLFDqkckTGofLPSjq6f8
It/QpiwtuGwimXuzoNqRFaeGq8OW41I+sCXHxLLDBE9lPjvGIE6GlxVFtbfTBFLr
qi7grcgwZKTxLncZzSxmJHseQKDrac/GQbBdd2c0OrRGiExvLfzg101q5U8qm0vk
OCfj6hSHTRvUzHYXylh1Y1RB4J2IUiA0AsUn
-----END CERTIFICATE-----

**Comment by zhanhb** [comment]
刚搜了一下，发现只有第一个你这里是没有的，后两个你这里已经有了，请忽略

**Comment by chengr28** [comment]
第一个中级证书是 Certification Authority of WoSign 根证书签发的，根证书被吊销了的话中级证书也不会有效，所以不需要单独加进去。
