### ISSUE TITLE
这是怎么回事？大佬能帮小白解决一下这个问题吗？

### ISSUE THREAD

**Issue by wizprabbfb** [chengr28/RevokeChinaCerts#146]
一开始运行bat还跑了一阵，之后就会这样：

System.IO.FileLoadException: 另一个程序正在使用此文件，进程无法访问。 (异常来自 HRESULT:0x80070020)
   在 LocalPolicy.COM.IGroupPolicyObject.Save(Boolean machine, Boolean add, Guid extension, Guid app)
   在 LocalPolicy.GroupPolicyObject.<Save>b__0()
   在 LocalPolicy.GroupPolicyObject.trycatch(Func`1 operation, String messageTemplate, Object[] messageArgs)
   在 LocalPolicy.GroupPolicyObject.Save()
   在 SoftCertPolicyAppender.SoftwareRestrictionPolicyController.AddCertRule(X509Certificate2 cert)
   在 SoftCertPolicyAppender.Program.Main(String[] args)
另一个程序正在使用此文件，进程无法访问。 (异常来自 HRESULT:0x80070020)Please select: Retry, Ignore or Abort (R|I|A)

**Comment by wizprabbfb** [comment]
现在一运行bat就变成如上了

**Comment by wizprabbfb** [comment]
是在这里https://github.com/chengr28/RevokeChinaCerts/releases/tag/v0.1.0.2下载的RevokeChinaCerts-0.1.0.2-bin.zip

**Comment by chengr28** [comment]
可以提供一下完整的命令吗？就像 https://github.com/chengr28/RevokeChinaCerts/issues/132

**Comment by chengr28** [comment]
如果还有问题，可以直接回复。
