### ISSUE TITLE
[已解决]win8.1运行提示【系统找不到指定的路径】的问题

### ISSUE THREAD

**Issue by Explorare** [chengr28/RevokeChinaCerts#15]
今天遇到的问题，运行后出现以下内容

系统找不到指定的路径。
'维护\RevokeChinaCerts-master\RevokeChinaCerts-master\Windows\' 不是内部或外部命令，也不是可
运行的程序
或批处理文件。
系统找不到指定的路径。
系统找不到指定的路径。

然后跳出了本地策略组编辑器。

昨天第一次运行正常，但是因为影响了goagent的功能无法修复然后就restore了。今天就没法再运行了。顺便求goagent证书的解决方案。只是删掉自带的CA然后重新安装生成的CA就OK了？

**Comment by xiaoneddy** [comment]
Windows 10 BUILD 10147 运行了还是可以安装百毒的相关软件。

**Comment by chengr28** [comment]
@xiaoneddy 请问具体是百毒的哪个软件？百毒的证书好像一直都有，而且有效期是 2017 年的

**Comment by xiaoneddy** [comment]
百毒云，百毒音乐卫士。今天刚装的windows 10，测试了一下发现百毒还能安装现在已经手动在策略组拉黑了百毒证书，阿里的aliedit这个好像也没拉黑听说在后台上传数据。

**Comment by phoeagon** [comment]
@xiaoneddy 这种情况为何不新开issue？另外能不能提供你下载的链接（或者把文件上传网盘

**Comment by chengr28** [comment]
@xiaoneddy ![2015-07-30-Windows_10-Block-360](https://lh3.googleusercontent.com/-LhtZNGPabFk/VboWsk5NtXI/AAAAAAACVho/JpWEGSpLe7k/w0/2015-07-30-Windows_10-Block-360.png)

这两天 Windows 10 正式版本发布，测试了一下，没有启用软件强制策略，看起来是没有问题的w
