### ISSUE TITLE
疑似伪证书

### ISSUE THREAD

**Issue by wongsyrone** [chengr28/RevokeChinaCerts#17]
访问twitter.com解析到85.10.218.163

C:\Users\home>nslookup twitter.com
服务器:  UnKnown
Address:  192.168.1.1

非权威应答:
名称:    twitter.com
Addresses:  85.10.218.163  <<-----------this ip addr
          93.186.115.155
C:\Users\home>nslookup twitter.com 8.8.8.8
服务器:  google-public-dns-a.google.com
Address:  8.8.8.8
名称:    twitter.com
Addresses:  198.20.78.170
          93.95.100.115

Subject: localhost
Issuer: localhost
Expires on: Feb 2, 2040
Current date: Jan 9, 2015
PEM encoded chain: -----BEGIN CERTIFICATE-----
MIICkzCCAfwCCQCz1C5dEU6UpDANBgkqhkiG9w0BAQUFADCBjTELMAkGA1UEBhMC
VVMxFTATBgNVBAgTDFNvbWVwcm92aW5jZTERMA8GA1UEBxMIU29tZXRvd24xDTAL
BgNVBAoTBG5vbmUxDTALBgNVBAsTBG5vbmUxEjAQBgNVBAMTCWxvY2FsaG9zdDEi
MCAGCSqGSIb3DQEJARYTd2VibWFzdGVyQGxvY2FsaG9zdDAeFw0xMjA5MTcwOTMx
NTVaFw00MDAyMDIwOTMxNTVaMIGNMQswCQYDVQQGEwJVUzEVMBMGA1UECBMMU29t
ZXByb3ZpbmNlMREwDwYDVQQHEwhTb21ldG93bjENMAsGA1UEChMEbm9uZTENMAsG
A1UECxMEbm9uZTESMBAGA1UEAxMJbG9jYWxob3N0MSIwIAYJKoZIhvcNAQkBFhN3
ZWJtYXN0ZXJAbG9jYWxob3N0MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC7
TpOd9R2qfp3nk5X2bHF8ef0SWe+iAQkBC6m6woq1vNvytBw0/YodQhr+23fmIhSW
+m21tRrdZqjtAiiETo5Y3Bb0P+fofvUDE17q5dH5z9Aysa+YK9SpAK3o81APCy4F
DdR38Tqst93Ik0vGwVFVOQBLU2Utzi7H+w0XUfbxAQIDAQABMA0GCSqGSIb3DQEB
BQUAA4GBALcBIuc9HLPn9975toa1SfRLb8NaKQqvAYuJTDaVY2BbueFwHcgvIyEQ
a6jkCnk39z6AgDj2n/80B7nN/mbYBtRnyN79xEi6tM/RVDQROLAA5Xd9Xr4bfNqR
nLNhXbpHuz6dgvB8Y2RpI5/5hC3J/vM93k4OLAE3CRaoggj0E98E
-----END CERTIFICATE-----

指纹：‎f9 cf fe c2 b9 d5 01 64 8e 77 03 e0 59 62 28 17 f7 6a b4 3f
指纹算法：sha1
序列号：‎00 b3 d4 2e 5d 11 4e 94 a4
签名算法：sha1RSA
签名哈希算法：sha1

**Comment by v998** [comment]
@wongsyrone 
localhost 大概是因為http server開啟了SSL/TLS支援
但網站本身沒有使用SSL/TLS，也就沒有放上Certificate
所以那個裝http server時openssl所generate出來的 certificate就是localhost

**Comment by wongsyrone** [comment]
估计如同 @v998  所言
@yfdyh000  我当时是访问那个德国ip得到的localhost证书

**Comment by chengr28** [comment]
http://www.solidot.org/story?sid=42606
其实就和之前 Apple 没有提供加密服务，强行访问时拿到不正确的证书是一样的道理……

**Comment by wongsyrone** [comment]
感谢大家，估计可以close了
