### ISSUE TITLE
Request Add Superfish CA to Base

### ISSUE THREAD

**Issue by Septembers** [chengr28/RevokeChinaCerts#19]
see http://www.cnbeta.com/articles/371863.htm
see https://www.v2ex.com/t/171859

**Comment by v998** [comment]
I am not sure if the CA is machine-independent...
http://blog.erratasec.com/2015/02/extracting-superfish-certificate.html

**Comment by chengr28** [comment]
Thanks for your report, certificate of Superfish has been added.
