### ISSUE TITLE
能否维护一份证书列表？

### ISSUE THREAD

**Issue by adoyle-h** [chengr28/RevokeChinaCerts#23]
因为貌似很难看出具体移除了哪些证书，这让我感到有些不放心。
希望能指明证书名称和来源。

P.S. 我是 mac 用户

**Comment by phoeagon** [comment]
https://github.com/chengr28/RevokeChinaCerts/wiki/ReadMe_Online(Chinese_Simplified)

-- 
Zhe Qiu

Institute of Parallel And Distributed Systems
@School of Software,
Shanghai Jiao Tong University

------------------------------------------
Keep it Simple, Stupid

----------------------------------
See also @phoeagon on foursquare, Twitter, linkedin, etchttp://about.me/phoeagon
Send encrypted emails to me with PGP 0x7F2E4AC8


2015-02-24 22:34 GMT+08:00 ADoyle <notifications@github.com>:

**Comment by chengr28** [comment]
证书列表的话 ReadMe 里其实都有……

Mac OS X 的情况比较特殊，因为本身系统是不能吊销外部导入的证书
所以只禁用了 CNNIC 和 UCA 还是 CFCA 的根证书，其它的证书默认是不受信任的

**Comment by adoyle-h** [comment]
了解，谢谢。
