### ISSUE TITLE
On Linux cert blacklisting

### ISSUE THREAD

**Issue by phoeagon** [chengr28/RevokeChinaCerts#25]
There seems to be multiple certificate databases on most major Linux distros and widely-used software.
 (http://blog.xelnor.net/firefox-systemcerts/, https://bugs.launchpad.net/ubuntu/+source/nss/+bug/593320) 
Most notable ones are:

+ System-wide CA-store. Usually reflected by `/etc/ca-certificates.conf`. This one looks pretty coarse to me and one has to either select or deselect a certificate. (I have no way to determine whether having an installed certificate *deselected* is the same with not installed at all or as *removing trust*. But chances are that I cannot test it out because CAs sign each other's CA Root certificate. Fiddling with this one is in *great danger* of interfering and being interfered by `ca-certificates` package.

+ Mozilla NSS DB, used by Chrome (in the user profile configuration folder) and Chrome (under `~/.pki/nssdb`), also available systemwide (`/etc/pki/nssdb`). To get consistent behaviour across applications, any revocation must at least be installed in all these three locations. This one supports more fine-grained support and can blacklist a specific certification (revoking trust instead of removing), the behavior of which is similar to that on Windows platform.

So there are these potential issues:
+ Can we revoke trust for the root CA cert from `/etc/ca-certificates.conf` or the best we can do is not to install it? (In the latter case, if the root CA cert is from another Root CA, we very probably end up trusting it).
+  How can we locate `nssdb`s scattered virtually everywhere? Only the Chrome one and the system-wide one seem easy to locate. Also `nssdb`s are undergoing a format upgrade such that we might very well run into incompatible DB versions even if we use `certutil` the official tool. Although the utility provides an `upgrade` switch, it'd be better not to upgrade it in case it breaks some 3rd party applications.

And the conclusion is, although writing code to overcome this is possible, it's very likely that we simply don't have the resources to test it out and make sure we cover all the cases mentioned above.

*Probably currently the best we can do is to document the above fact in README*

**Comment by phoeagon** [comment]
`/etc/ca-certificates.conf` rules certificate verification of *OpenSSL-based* applications, while `nssdb` those NSS-based ones. It's comparatively easy to fix the NSSDB one if we know the exact location (and hence we can fix for Firefox & Chrome) but those based on OpenSSL (wget/curl) would still suffer.

**Comment by dazzyd** [comment]
System wide CA management is different on different distribution.
For Arch Linux, simply copying cert to /etc/ca-certificates/trust-source/blacklist/ can revoke a cert.
