### ISSUE TITLE
运行RevokeChinaCerts_CodeSigning出错

### ISSUE THREAD

**Issue by AutobotsCT** [chengr28/RevokeChinaCerts#27]
管理员和普通用户都试过了，错误信息相同。如下：
Error: Failed to save to the destination store
CertMgr Failed
这个算不算成功呢？

**Comment by chengr28** [comment]
建议打开『运行』输入『certmgr.msc』在『不信任的证书』下的『证书』中看看是否存在有 Code Signing 的证书，Code Signing 的证书在 /Windows/Certs/CodeSigning 里有，或者 https://github.com/chengr28/RevokeChinaCerts/wiki/ReadMe_CodeSigning(Chinese_Simplified)#%E6%B6%89%E5%8F%8A%E7%9A%84%E8%AF%81%E4%B9%A6 这里也有证书列表

这个错误主要是有时重复添加了，或者删除吊销时会出现，具体的情况还要具体去看看w

**Comment by AutobotsCT** [comment]
嗯，已经成功添加进去了。
谢谢。
之前是想要测试set force模式来着，应该是重复添加报错的。
