### ISSUE TITLE
Access Denied on Windows 8.1

### ISSUE THREAD

**Issue by Jamesits** [chengr28/RevokeChinaCerts#30]
Windows 8.1, CodeSigning, force certificates policy, Administrator previlege given.
Most of them is successful, but there are something like:
```
1.System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT:
 0x80070005 (E_ACCESSDENIED))
   at LocalPolicy.COM.IGroupPolicyObject.Save(Boolean machine, Boolean add, Guid
 extension, Guid app)
   at LocalPolicy.GroupPolicyObject.<Save>b__0()
   at LocalPolicy.GroupPolicyObject.trycatch(Func`1 operation, String messageTem
plate, Object[] messageArgs)
   at LocalPolicy.GroupPolicyObject.Save()
   at SoftCertPolicyAppender.SoftwareRestrictionPolicyController.SetPolicyKey(St
ring path, String name, Object value, RegistryValueKind kind)
   at SoftCertPolicyAppender.SoftwareRestrictionPolicyController.AddCertRule(X50
9Certificate2 cert)
   at SoftCertPolicyAppender.Program.Main(String[] args)
```

If don't use force certificates policy, only three or some is successful, the rest of them output:
```
Error: Failed to save to the destination store
CertMgr Failed
```

**Comment by chengr28** [comment]
你好，抱歉这么久才回复……一直在忙另外一边的问题

关于这个具体不清楚具体是什么情况……实测 XP/Vista/7 不存在这个问题
Win 8/8.1 系的则会随机出现，可能需要去调查一下新系统的证书机制才能回复……

**Comment by wongsyrone** [comment]
我一直用win8.1，跟随系统补丁到最新，没发现类似问题，可以尝试打全补丁？我这里无法复现。
@Jamesits

**Comment by Jamesits** [comment]
@wongsyrone UAC 可以排除……无论是否用管理员权限运行均试过了。

**Comment by wongsyrone** [comment]
@Jamesits   
1.查查组策略是否有类似的限制
2.右键｜安全｜点击“添加”｜点击“高级”｜点击“立即查找” |选中“Authenticated Users"｜确定｜确定 
3. 查看批处理文件属性检查是否有“解除限制”按钮，查看NTFS权限
另外针对错误信息`System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))`搜索到官方文章https://social.msdn.microsoft.com/Forums/zh-CN/6229334e-d5ef-4016-9e7e-1c8718be8d43/access-is-denied-exception-from-hresult-0x80070005-eaccessdenied-in-vbnet，可以尝试一下

**Comment by chengr28** [comment]
更新补丁之后我这边的 Win 8.1 貌似没出现类似的情况了……大概是系统的证书处理有 Bug？
