### ISSUE TITLE
cannot block baidu guard

### ISSUE THREAD

**Issue by ProgramCaiCai** [chengr28/RevokeChinaCerts#31]
they are using new certificates  see sample at:http://anquan.baidu.com/weishi/

**Comment by ProgramCaiCai** [comment]
Sample of pure certificate: https://www.dropbox.com/sh/fsq712wwi7vrw23/AAAzKK8gkwsTsZsz7_lpbe27a?dl=0

**Comment by chengr28** [comment]
Thanks for your report, certificate of new Baidu CodeSigning has been added w
