### ISSUE TITLE
Error on mac

### ISSUE THREAD

**Issue by raighneweng** [chengr28/RevokeChinaCerts#32]
~ Raighne$ sudo /Users/-/Documents/RevokeChinaCerts_All.sh 
Password:
Error (2) reading Trust_Settings_All.plist.
RaighnedeMacBook-Pro:~ Raighne$

**Comment by chengr28** [comment]
请问 OS X 是什么版本的？有可能是因为系统版本对不上读取不了……
这个 plist 配置文件是 Mavericks 上导出的

**Comment by phoeagon** [comment]
@htkme Does your fix result in a regression in prior versions? (Or so far as I can see you just used quotes to contain the paths right?

**Comment by ntkme** [comment]
@phoeagon `dirname` is a general unix command and it should work anywhere.
