### ISSUE TITLE
mac操作以后，goagent的证书怎么处理，访问不了https twitter了

### ISSUE THREAD

**Issue by lifeva** [chengr28/RevokeChinaCerts#33]

**Comment by chengr28** [comment]
OS X 上并没有吊销 GoAgent 的证书，只对系统自带的根证书进行了禁用
可能是因为导入 plist 之后覆盖了原来的证书设定，可能需要重新导入 GoAgent 的证书

**Comment by chengr28** [comment]
刚才更新的 OS X 版本 https://github.com/chengr28/RevokeChinaCerts/tree/master/Mac 已经不会直接覆盖原有设置，不过因为之前的版本已经覆盖掉了没法还原……GoAgent CA 可能需要重新导入，或者重新部署一遍 GoAgent 再清空所有浏览器数据和系统缓存应该就行了
