### ISSUE TITLE
请问怎么测试是否成功了呢？

### ISSUE THREAD

**Issue by moye26** [chengr28/RevokeChinaCerts#34]
请问怎么测试是否成功了呢？

**Comment by Septembers** [comment]
https://github.com/chengr28/RevokeChinaCerts/wiki/ReadMe_Online(Chinese_Simplified)

**Comment by chengr28** [comment]
楼上的链接里，不少具体证书都有附带测试网址，可以直接打开测试网址测试效果
或者最简单就是去找 CNNIC https://www.cnnic.net.cn
