### ISSUE TITLE
Where is the crt file for Baidu WACC service?

### ISSUE THREAD

**Issue by weakish** [chengr28/RevokeChinaCerts#41]
I cannot figure out which one is the cert for Baidu WACC service under [Windows/Certs/Online][certs]

[certs]: https://github.com/chengr28/RevokeChinaCerts/tree/master/Windows/Certs/Online

**Comment by weakish** [comment]
Found. There is a prefix. `[Suspicious]WaccBaiduCom.crt`

**Comment by chengr28** [comment]
因为 CertMgr 工具导入的时候需要 crt 证书文件，所以只要需要导入吊销的肯定都有 =_/=
