### ISSUE TITLE
能否让用户选择恢复部分证书？特别是涉及网银的证书

### ISSUE THREAD

**Issue by himandy** [chengr28/RevokeChinaCerts#44]
我之前在windows下面把3个bat都允许了一遍。后来，发现农行网银打不开了，提示证书有问题。我在RevokeChinaCerts解压包中搜了一下关键词ABC，发现了3个名字当中有ABC的证书。另外，发现RevokeChinaCerts_Organization.bat这个文件里面也有涉及ABC的关键字。估计这是跟农行网银有关的。

于是，我再运行了一遍Organization.bat，restore恢复了所有修改，现在网银可以用了。我希望可以只恢复部分网银的证书。不知道可不可以？

**Comment by chengr28** [comment]
参见 ReadMe 中 [Choice version](https://github.com/chengr28/RevokeChinaCerts/wiki/ReadMe_Organization(Chinese_Simplified)) 的介绍

**Comment by himandy** [comment]
谢谢，之前已留意到Choice version，貌似是逐条让用户判断是否执行。如果能单独对某个证书进行操作就好了。不过现在这个工具已经帮了很多的忙，我的电脑速度快了很多。
