### ISSUE TITLE
小白求教……关于 Firefox + GoAgent

### ISSUE THREAD

**Issue by vxxholic** [chengr28/RevokeChinaCerts#45]
0.按照我的理解，GoAgent CA相当于自签名证书，应该不会被用于中间人攻击啊，为什么您要建议吊销

1.执行了您推荐的操作以后，访问twitter显示
“此连接不受信任
您想使用 Firefox 安全连接至 twitter.com，但是我们无法确认此连接是否安全。
通常，当您尝试安全连接时，站点会出示受信任的凭据，以证明您访问的是正确的位置。然而现在，此网站的身份无法核实。”
我应该如何操作？去找靠谱的证书下载下来导入吗…………

**Comment by v998** [comment]
0. 
GoAgent CA可能是原有的..
而那个原有的, private key已经全世界都知道，不安全

**Comment by sdc6882278** [comment]
现在已被证明这个自签名证书默认存在重大缺陷，会导致中间人进攻。只要删除目录里面的ca文件，再次运行会重新生成新的ca证书，这个证书是没有问题的，然后导入浏览器即可。

发自我的 iPad

**Comment by chengr28** [comment]
正如楼上所说，默认 GoAgent CA 的私钥是路人皆知，如果部署 GoAgent 后又被一些别有用心的人利用，那么将会导致网站被中间人攻击，就是为了防止此类情况才把默认证书吊销掉的，GoAgent 官方现在也不推荐使用默认证书了
解决方法 [ReadMe 文档](https://github.com/chengr28/RevokeChinaCerts/wiki/ReadMe_Online(Chinese_Simplified))里有提到：`Extended 版和 All 版会自动吊销 GoAgent 自带的 GoAgent CA 证书，为免使用 GoAgent 时出现错误同时也为了系统加密连接的安全强烈建议更换其自带的 CA 根证书。关闭所有 GoAgent 程序，进入其 local 目录删除 CA.crt 以及整个 certs 目录，然后清空所有浏览器数据重启 GoAgent 和浏览器即可` Firefox 可能需要重新按照教程部署一次 GoAgent

**Comment by vxxholic** [comment]
感谢各位的耐心解答，现在问题已经解决了

用 Chrome + Goagent打开 facebook 和 twitter 以后，CA.crt 和 certs 目录就会自动生成出来，然后再打开 FireFox->选项->高级->加密->查看证书->证书机构->导入证书, 选择local\CA.crt, 勾选所有项，导入就ok了

如果有【并没有…】其他使用 Firefox 的小白遇到这种问题，可以参考下..
