### ISSUE TITLE
the Mac version scripts does Not works on Mozilla Firefox

### ISSUE THREAD

**Issue by wisicn** [chengr28/RevokeChinaCerts#46]
after run the scripts on Mac OS X, the Google Chrome and Safari can successfully get the CNNIC Root CA warning, while the Mac OS X Mozilla Firefox still trust the CNNIC CA. I have to de-trust/delete the CNNIC CA manually in Firefox.

**Comment by ntkme** [comment]
Firefox has its own certificate validation mechanism, thus it does't respect system settings. We can dig into how Firefox stores its settings on Mac and try to get it automated by script.

**Comment by phoeagon** [comment]
Firefox should work if you try the Linux NSS revocation tool. If you are a
proficient user, please contact us for a more detailed manual on this.

**Comment by wisicn** [comment]
the [wiki](https://github.com/chengr28/RevokeChinaCerts/wiki/ReadMe_Online#usagewithout-automation-tools) works well for me. you made a awesome automation tools plus a detailed documents. thank you very much.
