### ISSUE TITLE
Any justification other than "SSL racism"?

### ISSUE THREAD

**Issue by romanrm** [chengr28/RevokeChinaCerts#47]
For example what fault do you find with Certification_Authority_Of_WoSign? Only CNNIC has been "in the news". Others should be considered fine, unless proven otherwise. If you don't agree, then you might as well just revoke all certs altogether and disregard the entire CA system. (Which might not a terrible idea by itself, but is a topic of another discussion).

**Comment by v998** [comment]
WoSign is a Chinese company.
It may compromise with the evil government
Then MitM on HTTPS connections behind the GFW would be possible. 
(Actually, it had happened before, Google, Github, Hotmail, Facebook, iCloud were targeted, but with self-signed certs which is not trusted by general browsers)
(and GitHub was recently hit by a DDoS, by man-in-the-side attack, Javascript was inserted with malicious code into different sites operating within China)

I know the current CA system is not safe, 
but with GFW and Chinese CAs, Chinese users are more likely to be a unwitting victim of MitM. 

We are just protecting ourselves.

**Comment by wisicn** [comment]
this is the statement on WoSign's website "沃通电子认证服务有限公司(WoSign CA Limited)成立于2002年，是同时获得国内电子认证服务许可证(由工信部颁发)和通过国际认证的证书颁发机构(CA)。"

so  Wosign is under the control of PRC MIIT. This is why I don't trust the Wosign CA. and in my own opinion, any CA issued by a organization inside PRC should not be trust any more.
However, this is a open source project, you can feel free to fork the RevokeChinaCerts project and ename it to RevokeCNNIC or whatever, and make it a Revoke CNNIC only software, people who have the same opinion with you will use your github repository.  and also, you can send pull request to the owner of chengr28/RevokeChinaCerts too, and let the owner and the community to decide if it will be merge. 
And  I will also fork current RevokeChinaCerts which will revoke all Chinese Certs in my own github repository. 
Man, remember, this is open source github community,  just follow the github rule please, and I totally agree with your idea: "revoke all certs altogether", go ahead, fork or create a github project,  show me the fucking code in Github,.

**Comment by phoeagon** [comment]
Personally I do not believe these CAs would contrive to issue fraudulent certificates for malicious use intentionally (unless concrete evidence presents of course), just as I don't think NSA would use the USA government CA for eavesdropping. However I find it very hard to convince other Chinese users on this.
