### ISSUE TITLE
OSX Trust Settings Import Error

### ISSUE THREAD

**Issue by nshobe** [chengr28/RevokeChinaCerts#48]
Just had this run on our entire office since we deal with Chinese data/sites on a semi-regular basis. I'm getting this error on roughly half of our machines (OSX 10.6/7/8/9/10 varieties present and I haven't noticed a pattern yet):

```./import-trust-settings.sh: line 5: 21573 Segmentation fault        "$SOURCE_DIR/libexec/security-trust-settings-merge" "$TrustSettingsExported" "$TrustSettings" "$TrustSettingsMerged"
SecTrustSettingsImportExternalRepresentation: The Trust Settings Record was corrupted. ```

Then it goes on to pass some URLs and fail others.

Sorry if there's some typos, that was copied over from a screenshot I received from a user. I haven't been able to recreate this issue on machines which worked fine the first time, nor have I figured out where the conflict is yet. Maybe it has to do with a browser being up and running?

**Comment by ntkme** [comment]
That binary file is build on OS X 10.10 and I did't have old OS X to test it, but you can try build it yourself and see what happens.

https://github.com/ntkme/security-trust-settings-tools

Later I'll try get a build that works for old OS X.

**Comment by ntkme** [comment]
I recompiled the binaries with `DEPLOYMENT TARGET = 10.6`. Could you test it?

**Comment by nshobe** [comment]
I'll give it a go Monday and report back.

**Comment by nshobe** [comment]
Looks to be fixed now. I re-ran it on a few machines and I'm now getting successful import results. I'm having sites fail the testing, but I feel that's an unrelated issue. Closing this issue.
