### ISSUE TITLE
online cert of HK and TW

### ISSUE THREAD

**Issue by hikaru613** [chengr28/RevokeChinaCerts#49]
The online cert issued by HK, Macao and Taiwan( especially Taiwan) should not be included. unless it proved to be faked.

**Comment by v998** [comment]
> WoSign should not be included too!
Well, in this case, **you should use our base or extended version** instead of all version.

**Comment by phoeagon** [comment]
We never recommend that you use the ALL version. On the contrary, we urge you to stay away from that revocation set.
