### ISSUE TITLE
运行rooted.sh提示 no such file or directory

### ISSUE THREAD

**Issue by himandy** [chengr28/RevokeChinaCerts#50]
我在Android手机使用terminal emulator for Android运行git clone https://github.com/chengr28/RevokeChinaCerts.git，结果显示/system/bin/sh: git: not found.
于是，我把文件下载到sd卡，解压，cd进入了extended目录，再运行./rooted.sh，结果显示：/system/bin/sh: ./rooted.sh: No such file or directory.

我手机已root，请问应该怎样解决？

**Comment by hikaru613** [comment]
copy pubkey_blacklist.txt , serial_blacklist.txt 到
/data/misc/keychain/

**Comment by himandy** [comment]
刚才复制过去，发现keychain文件夹下面已经有这两个文件，于是选覆盖。重新运行./rooted.sh，仍然是No such file or directory.

已经存在的2个txt文件，会不会是我之前在Root Explorer里面执行过rooted.sh的时候已经生成了呢？当时提示rooted.sh已执行，但是没有任何执行成功的提示。我查看了一下，CNNIC这个证书还是正常使用的，这表示代码的执行没有达到效果？

**Comment by phoeagon** [comment]
git的问题，说明你机子上没装git。你不如就download 源码zip文件吧。
本来就会有两个文件，确实是应该覆盖上去。装完请重启。

**Comment by hikaru613** [comment]
I believe must of android system don't have bash and openssl

**Comment by himandy** [comment]
嗯，应该没有装git。我是download源码zip，然后复制到sd卡再解压到。但是无法运行rooted.sh。我检查一下有没有bash和openssl

**Comment by phoeagon** [comment]
@hikaru613 @himandy No no no, you run the git commands and `rooted.sh` on your PC, which should have ADB connection to your phone.

**Comment by phoeagon** [comment]
@himandy 或者preferably，直接把prebuilt下面对应的extended/all/base文件里的两个blacklist.txt放进去就好了。
