### ISSUE TITLE
运行提示error: device offline

### ISSUE THREAD

**Issue by SamWitwicky** [chengr28/RevokeChinaCerts#53]
运行adb push pubkey_blacklist.txt /sdcard/pubkey_blacklist.txt的时候提示error: device offline

**Comment by phoeagon** [comment]
adb其他操作能做嘛？

**Comment by SamWitwicky** [comment]
可以。
adb使用的是绿色版的。

**Comment by phoeagon** [comment]
adb devices輸出什麼？

**Comment by Septembers** [comment]
需要安装[驱动](https://developer.android.com/tools/extras/oem-usb.html)才能使用adb

**Comment by SamWitwicky** [comment]
多谢提示adb的原因，现在已经弄好。
最初adb devices显示device offline
更新sdk之后adb devices显示device unauthorized.
禁用Revoke USB debugging authorization，重启了adb server之后，adb devices状态正常。
