### ISSUE TITLE
原来的证书列表和测试URL到哪里去了？ 

### ISSUE THREAD

**Issue by percyalpha** [chengr28/RevokeChinaCerts#55]
现在这样 https://github.com/chengr28/RevokeChinaCerts/blob/master/Shared/Certificates/Severity.High.md 通过CN比较难看清楚到底是哪个机构颁发的。 请问原来的列表和测试URL能提供下么？

**Comment by chengr28** [comment]
关于这个……原来维护列表的成本太大，所以才做成现在这种统一的数据库。测试 URL 的话一会儿去改一下 Wiki 那边加回去，不过其实原本就不多，参见 https://github.com/chengr28/RevokeChinaCerts/blob/master/Linux/validator.sh 脚本里有几个，至于原来那种列表应该是不会再加回去了

**Comment by chengr28** [comment]
列表已经添加进去了，参见 https://github.com/chengr28/RevokeChinaCerts/wiki/ReadMe_Online#about-certificates 如果 Name 那里是可以点击的就说明可以在线测试证书
感谢你的反馈w
