### ISSUE TITLE
RevokeChinaCerts 在windows 10环境下不能有效阻止流氓软件

### ISSUE THREAD

**Issue by xiaoneddy** [chengr28/RevokeChinaCerts#60]
![2015-06-23 14_42_12-program manager](https://cloud.githubusercontent.com/assets/12034676/8300383/c07ffc8e-19b6-11e5-9a1f-a79e023402ab.png)

**Comment by v998** [comment]
流氓软件真的会有签署么....

**Comment by chengr28** [comment]
Windows 10 的话几个月前的测试版测过是可以正常吊销掉的，当然现在也更新过很多测试版了不好说……可能得等到正式版本发布的时候才会有定论。或者这样，想到了两个可能性：
* 一开始询问是否使用软件强制策略屏蔽软件的时候，建议选择 N 采用传统的证书吊销方法，因为那个软件强制策略工具的操作比较底层，新平台是否能工作正常不好说，不过传统的证书吊销方法成功率更高，所以可以试试看看
* 有些搜索引擎或者下载网站提供的软件，可能经过下载站自己的签名并打包，这样由于安装程序本身是下载站的证书而不是软件的证书，有可能会导致最终还是没能阻止程序的运行

**Comment by xiaoneddy** [comment]
![2015-06-26 10_03_57-](https://cloud.githubusercontent.com/assets/12034676/8369379/2d123570-1beb-11e5-9cf9-af2169b82533.png)

**Comment by chengr28** [comment]
我不是说不支持，而是『建议选择 N 采用传统的证书吊销方法』试试看

**Comment by chengr28** [comment]
![2015-07-30-Windows_10-Block-360](https://lh3.googleusercontent.com/-LhtZNGPabFk/VboWsk5NtXI/AAAAAAACVho/JpWEGSpLe7k/w0/2015-07-30-Windows_10-Block-360.png)

这两天 Windows 10 正式版本发布，测试了一下，没有启用软件强制策略
看起来是没有问题的w
