### ISSUE TITLE
微软最近推送了数个奇怪的证书

### ISSUE THREAD

**Issue by Jamesits** [chengr28/RevokeChinaCerts#61]
https://hexatomium.github.io/2015/06/26/ms-very-quietly-adds-18-new-trusted-root-certs/

**Comment by yfdyh000** [comment]
我的 Windows 8.1 简体中文版，自动更新开启状态，用 certmgr.msc 或者 [RCC](http://www.wilderssecurity.com/threads/rcc-check-your-systems-trusted-root-certificate-store.373819/) 工具，没有找到他所说的证书。

**Comment by v998** [comment]
表示早几天知道了....当时查了一下GDCA..
不过8.1就是没更新...当时(和现在)也不能确认..

http://www.plaintextcity.com/2015/06/june-23-2015-microsoft-certificate.html

**Comment by yfdyh000** [comment]
用 `certutil.exe -syncwithwu .\wu` 的确下载到了……
352个文件，其中的 0f36385b811a25c39b314e83cae9346670cc74b4.crt 就是 GDCA TrustAUTH R5 ROOT，与在 http://www.gdca.com.cn/certdownload/caCertDownloadAction.do 的 GDCA TrustAUTH R5 ROOT 相同，所有颁发策略……

**Comment by chengr28** [comment]
刚才已经推送了 **Microsoft Certificate Trust List Update(2015-06-23)** 的更新，把 **GDCA TrustAUTH R2/R5 ROOT** 加进去了，至于 WoSign 那两个其实 All 版本来就有……所以没动

**Comment by chengr28** [comment]
https://root4evtest.wosign.com 和 https://root5evtest.wosign.com
貌似多上几次就系统就自动更新了……也不用特意去找 =_/=

**Comment by frjalex** [comment]
插句话，谁知道那个RXC-R2的证书是干什么的？这种可疑的证书需不需要也直接吊销？
  2c8affce966430ba04c04f81dd4b49c71b5b81a0   RXC-R2                         US

**Comment by chengr28** [comment]
Cisco CA/B-F Root CA
C=US, O=Cisco Systems, CN=Cisco RXC-R2
https://www.cisco.com/security/pki/policies/CiscoRXC-CP.pdf

**Comment by frjalex** [comment]
@yfdyh000 补充一句，https://hexatomium.github.io/2015/06/26/ms-very-quietly-adds-18-new-trusted-root-certs/ 一文中的"my good old **RCC** scanner"可以从 http://trax.x10.mx/dl_rcc.php?appname=rcc.zip下载。

**Comment by frjalex** [comment]
@chengr28 谢谢，受教了
