### ISSUE TITLE
Do I need to right click "Run as administrator" ?

### ISSUE THREAD

**Issue by v998** [chengr28/RevokeChinaCerts#62]
![image](https://cloud.githubusercontent.com/assets/7825360/8403523/2fd8596c-1e78-11e5-8dd0-a5751bc31e33.png)

Am I **required** to do this?
Will there be any difference for _Run as admin_ and _Run as current user_?

*I am not able to find it in the Wiki or README.md
*I am asking about all the types (including `CodeSigning`, `Firefox`, `Online` and `Organization`)

**Comment by chengr28** [comment]
* 对于传统使用 CertMgr 加入吊销列表的之前有人提过 Issue https://github.com/chengr28/RevokeChinaCerts/issues/1 一般来说直接运行即可不需要管理员权限，因为就算用了管理员权限修改的也只是本账号的证书策略，或者这样说……Windows 里似乎是为每个用户维护一份不相关的名单，一个帐号的无法修改其它账号的名单
* 对于程序强制策略 `CodeSigning` 和 `Organization` 里则默认要求管理员权限运行

**Comment by v998** [comment]
![image](https://cloud.githubusercontent.com/assets/7825360/8431124/e144b5be-1f69-11e5-9496-30d26a0a79e3.png)
What about this screen?
<hr>
假若不使用程序強制策略，則可不使用管理員權限運行？

**Comment by v998** [comment]
![image](https://cloud.githubusercontent.com/assets/7825360/8431124/e144b5be-1f69-11e5-9496-30d26a0a79e3.png)
可是會出現此視窗 (`ONLINE`)
<hr>
另外，
假若 `CodeSigning` 和 `Organization` 不使用程序強制策略，則可**不**使用管理員權限運行？

**Comment by chengr28** [comment]
*Online 会出现这个是因为在吊销之前会运行 KB931125 补丁更新系统的证书列表，和吊销的部分不一样，吊销部分的权限由批处理的运行权限决定
* 应该是的

**Comment by v998** [comment]
这部份应否加进Wiki内？

**Comment by chengr28** [comment]
改好了……加了一句提醒w
