### ISSUE TITLE
2345 的证书似乎没有放到该项目里

### ISSUE THREAD

**Issue by SkyZH** [chengr28/RevokeChinaCerts#63]
今天早晨我灵机一动冒着电脑被安装全家福的风险试着安装了现今中国最大流氓软件企业 2345 的好压……结果 UAC 竟然没有报警……     
于是我一看这个项目的 Wiki 里有 2345 的证书……但是程序目录下没有……也没有成功添加……     
经过比对 Wiki 的 Fingerprint 和 好压里证书的 Fingerprint 相同。所以，自己添加到 Untrusted Certificates 里面，再传一份以供参考……     
[好压等软件下载](http://www.2345.com/product/)
[提取的证书](http://pan.baidu.com/s/1txuge)
提取码是 d5f8

**Comment by chengr28** [comment]
2345 的证书正如 Wiki 所说 CodeSigning 里是有的
正常来说如果使用了 CodeSigning 版本成功加入到证书吊销列表里，应该是可以成功阻止的
不过之前有研究过 Windows 的验证机制，不开全局强制程序策略的话貌似无法做到滴水不漏……
