### ISSUE TITLE
测试发现 wosign.com 没有通过

### ISSUE THREAD

**Issue by JohnHwee** [chengr28/RevokeChinaCerts#64]
➜  Mac git:(master) ./test-trust-settings.sh 
✓ https://cs.cfca.com.cn/
✓ https://www.cnnic.cn/
✓ https://cstest.cfca.com.cn/
✓ https://211.146.10.133/
✓ https://evdemo.cnnic.cn/
✗ https://www.wosign.com/
✓ https://mail.ztgame.com/
✓ https://ibanks.bankofshanghai.com/
? https://www.sheca.com/
└── curl: (28) SSL connection timeout

**Comment by ntkme** [comment]
https://github.com/chengr28/RevokeChinaCerts/blob/master/Mac/README.md

``` sh
MODE=strict ./build-trust-settings.sh
./import-trust-settings.sh
```
