### ISSUE TITLE
CNNIC is still trusted on OS X 10.10.5

### ISSUE THREAD

**Issue by fhoshino** [chengr28/RevokeChinaCerts#65]
On OS X 10.10.5, after running the script following the guide here:
https://github.com/chengr28/RevokeChinaCerts/tree/master/Mac

Even after using "MODE=strict ./build-trust-settings.sh"
CNNIC certs are still trusted on Safari.

**Comment by ntkme** [comment]
Did you run `./import-trust-settings.sh` after rebuilding the settings?

I simply cannot reproduce this issue.

**Comment by fhoshino** [comment]
Yes, what I have run:
./import-trust-settings.sh
sudo security trust-settings-import -d TrustSettings.plist
MODE=strict ./build-trust-settings.sh
./import-trust-settings.sh

**Comment by ntkme** [comment]
Confirmed.

CIINC ROOT is no longer bundled with 10.10.5. Adding "CNNIC SSL" intermediate CA certificate to blacklist fix this issue.

**Comment by ntkme** [comment]
Close by #66.

**Comment by jnozsc** [comment]
still have same issue for macOS sierra.
is it ok to reopen this issue or create a new one?

**Comment by jnozsc** [comment]
``` 
~/RevokeChinaCerts/Mac   master ●  ./import-trust-settings.sh
...Trust Settings exported successfully.
...Trust Settings imported successfully.
 ~/RevokeChinaCerts/Mac   master ●  sudo security trust-settings-import -d TrustSettings.plist
...Trust Settings imported successfully.
 ~/RevokeChinaCerts/Mac   master ●  MODE=strict ./build-trust-settings.sh
 ~/RevokeChinaCerts/Mac   master ●  ./import-trust-settings.sh
...Trust Settings exported successfully.
...Trust Settings imported successfully.
 ~/RevokeChinaCerts/Mac   master ●  ./test-trust-settings.sh
✓ https://211.146.10.133/
✓ https://cstest.cfca.com.cn/
✓ https://cs.cfca.com.cn/
✓ https://www.sheca.com/
✓ https://www.wosign.com/
✗ https://evdemo.cnnic.cn/
✗ https://www.cnnic.cn/
? https://ibanks.bankofshanghai.com/
└── curl: (35) Server aborted the SSL handshake
? https://mail.ztgame.com/
└── curl: (28) Connection timed out after 60002 milliseconds
```

**Comment by ntkme** [comment]
@jnozsc See #81.

**Comment by jnozsc** [comment]
thanks
