### ISSUE TITLE
Can't install qq game even after restoration. 

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [chengr28/RevokeChinaCerts#67]
Windows 8.1 I used this tool but now qq game can't update saying "administrator has blocked this application. Publisher not trusted."

So I ran all 4 bat and choose restore for every one of them. Still, I get the same error when using qq game.

My dad is very mad coz he only wants to play qq game. 

Need serious help. QQ game is life.

**Comment by chengr28** [comment]
You may need to restore with setting force policy or not(Y/N), both.
After running batches, reboot the system.

If you still got the same error message, you can go to `certmgr.msc` - `Certificate revocation lists (CRLs)` and search certificates about `Tencent`. Delete them from CRLs and reboot system to solve this problem.

**Comment by GreatBigWhiteWorld** [comment]
Thank you. I had to find tencent in that list and delete it.
