### ISSUE TITLE
RevokeChinaCerts对edge浏览器无效

### ISSUE THREAD

**Issue by SamWitwicky** [chengr28/RevokeChinaCerts#70]
不知是edge浏览器的原因还是RevokeChinaCerts的原因，在执行过证书移除之后使用cnnic网站测试，在edge浏览器下依然可以打开

**Comment by chengr28** [comment]
Edge 使用的是 Windows 系统内置的证书信任列表，测试过是没有问题的
建议使用完后清空所有浏览器数据并重启系统再试试

**Comment by SamWitwicky** [comment]
不行唉，我下午就已经清空重启试过了。
你不妨再测试下，看https://www.cnnic.cn的访问情况。

**Comment by SamWitwicky** [comment]
![capture](https://cloud.githubusercontent.com/assets/9652173/11318350/14d53598-908a-11e5-9bc1-6a705e90767d.PNG)
![capture1](https://cloud.githubusercontent.com/assets/9652173/11318351/14ffa472-908a-11e5-93a2-1cd125aec515.PNG)
上面两张图分别是我在edge和chrome下测试所得的结果。

**Comment by chengr28** [comment]
建议检查 Edge 浏览器的设置是不是有问题，是不是有软件干扰了 Edge 浏览器的工作，或者重置一下 Edge 浏览器看看怎么样
Chrome 和 Edge 一样都是使用 Windows 内置的证书信任列表，Chrome 下可以正常工作说明 RevokeChinaCerts 这边是成功将Windows 内置证书信任列表里的 CNNIC 吊销掉了的

**Comment by chengr28** [comment]
突然想多问一句……用的是 Windows 10 version 1511 吗？

**Comment by v998** [comment]
Interesting..can confirm.

IE&Edge do not block those revoked certs.
Chrome blocks successfully.
Tested on Windows 10 (Version 1511) Traditional Chinese.

**Comment by chengr28** [comment]
嗯升级之后实测是一样的结果……具体的情况是 Edge 和 IE 浏览器虽然也会禁止 CRL 吊销列表里证书的使用，但似乎会默认信任所有 Microsoft 根证书列表中的证书而不会理会 CRL 中是否已被吊销，Chrome 等其它浏览器不受影响
不知道这个是不是 TH2 ISO 被撤下的其中一个原因，看样子应该是 Microsoft 自己的锅了……

**Comment by wansen** [comment]
TH2 ISO 系统，不仅是 Edge，IE也存在这样的问题；但Chrome没有问题

**Comment by SamWitwicky** [comment]
抱歉，反馈的时候忘了说明版本信息，用的的确是TH2。

**Comment by q158073378252010** [comment]
火狐浏览器更佳适合

**Comment by v998** [comment]
（看到楼上提到火狐，说点题外话）
火狐用的是自家的NSS...
应该不会用到系统的SChannel..
所以理应火狐不会受此bug影响..

至于SeaMonkey...
开发好像不太活跃..
另外安装包没有签署..安全性不足.. **不推荐**
<hr>
究竟微软知道这个bug没有？
有没有人向微软回报过？

**Comment by yfdyh000** [comment]
问题重现，TH2。
翻了 http://blogs.technet.com/b/secguide/archive/2015/11/13/security-baseline-for-windows-10-threshold-2-draft.aspx ，没发现什么有价值的信息。`The only differences between the TH1 final and the TH2 draft are the new settings that apply only to TH2.`
感觉可以在该博客中回复，应该是微软官方在维护并且会回复。

**Comment by q158073378252010** [comment]
我想我们可以去下面的链接下载与mozilla 有关的东西，其中也包括火狐浏览器以及seamonkey 。我想虽说软件安装包没签名，https应该可以提供数据传输不被修改的可能。：https://archive.mozilla.org/pub/seamonkey/releases/

**Comment by v998** [comment]
不知道自动更新又是从哪儿拿的...
希望也是HTTPS吧...
http://seamonkey.ilias.ca/tutorials/upgrading

**Comment by q158073378252010** [comment]
不要启用自动更新。自动更新不安全。因为seamonkey属于开发者套件。就像官网说的，浏览网页只是他的一个功能而已

**Comment by v998** [comment]
既然是开发者套件就别用作上网吧...
估计它也不会急着修补漏洞的..

**Comment by q158073378252010** [comment]
话到没错。但剑走偏锋。我想比较冷门的东西，估计也没人去污染它。

**Comment by chengr28** [comment]
装了那个修复 TH2 ISO 错误的 KB3120677 表示并没有效果……还是照样放行

**Comment by q158073378252010** [comment]
我在想 win10 这么差干嘛不用win7

**Comment by chengr28** [comment]
![Image](https://lh3.googleusercontent.com/-wyHtm2fv95k/VlWbQPM3AII/AAAAAAAAC9w/hRDlnq7fkLw/w0/15%2B-%2B1.jpg)

惊觉 [可能只有中文版系统才会出现这个问题](https://plus.google.com/+GrantDong/posts/aJip3UxcPNM)……

**Comment by chengr28** [comment]
@q158073378252010 毕竟是新的操作系统……无论怎么差，属于支持平台之一，也是得进行支持的……就像 XP 一样

**Comment by chengr28** [comment]
刚才推送了更新，批处理现在会将证书添加到全局的 CRL 中，实测可以保证 1511 系统 Edge/IE 可以正常阻止被吊销证书网站的浏览。至于 Edge/IE 不检查当前用户的 CRL……或许报告给微软比较好？

**Comment by v998** [comment]
当然要报告...
问题是如何报告..

**Comment by yfdyh000** [comment]
我已经在那篇博客的评论说了，正在等待回复。

**Comment by wongsyrone** [comment]
@yfdyh000 那篇博客有回复了，问详细重现步骤呢

**Comment by yfdyh000** [comment]
@wongsyrone 感谢。意外的没有邮件提醒。28已经详细回复了，继续等待。

**Comment by lainredsonic** [comment]
可以不用作者的revoke，直接把要删除的证书删除掉，然后在组策略里面禁用“自动证书更新”就不会再自动安装任何证书了。也不用担心已有CA证书会过时，因为CRL，OCSP仍然会正常自动查询。需要更新的话可以安装RSAT使用certutil -generateSSTFromWu CA_roots.sst 从微软服务器下载300多个信任的CA证书，然后双击roots.sst，按需导入更新。

**Comment by chengr28** [comment]
@lainredsonic 吊销的优先级是最高级的，与其这样处处小心，直接 revoke 掉不是更好？自动证书还是正常工作，证书列表还是可以获得更新

**Comment by chengr28** [comment]
等了这么久巨硬的员工直接跳过了……那次之后 Win10 上的 Edge/IE 貌似也有安全更新，不知道有没有修好了，还是说这个真的是 Feature..

**Comment by yfdyh000** [comment]
嗯，似乎无视了，等了很久都没回复……等一月的更新看看吧，或许补丁还没做好/发布呢……

**Comment by chengr28** [comment]
这个 Issue 先关掉了……现在添加到计算机全局列表并没有出现这个问题
剩下的就只能寄望微软修复了……
