### ISSUE TITLE
Win10下运行吊销工具的时候拒绝访问

### ISSUE THREAD

**Issue by lqf96** [chengr28/RevokeChinaCerts#72]
rt（是以管理员权限运行的，无论哪个选项都不能运行）
![10](https://cloud.githubusercontent.com/assets/11476527/11553712/46735bc0-99cc-11e5-9a1b-61aad7e614f9.png)

**Comment by chengr28** [comment]
试试直接运行和以管理员运行 Tools 目录下的 CertMgr.exe 和 CertMgr_x86.exe 看是不是被系统阻止了……最新版本会将证书添加到计算机全局列表中，这个过程需要管理员权限，然而实测过 Windows 10 没问题才上线的……

**Comment by lqf96** [comment]
问题已经找到了，在Cygwin下Clone的repo，由于工程中.exe文件没加执行权限，而cygwin完整复制了git中文件的权限，所以无法运行...虽然在windows下clone的大部分都用git for windows估计木有这个问题但还是建议给win下所有可执行文件和脚本加执行权限...

**Comment by chengr28** [comment]
Windows 下的使用方法基本都是直接从网站 Download ZIP 的……似乎并不会 Clone 什么
