### ISSUE TITLE
创建 CONTRIBUTING.md 文件，并对添加证书、贡献代码等进行相关说明

### ISSUE THREAD

**Issue by DzyF** [chengr28/RevokeChinaCerts#73]

**Comment by chengr28** [comment]
不好意思拖了段时间才回复……

* 如果单纯只是想自行更新全平台可用的吊销列表，可以参照 https://github.com/chengr28/RevokeChinaCerts/tree/master/Shared/Certificates 页面的方法在 Linux 在进行操作进行更新
* Windows 平台下的 Organization 和 CodeSigning 自行更新则需要把证书重命名为指纹值放到相应的目录内，并添加/修改对应 bat 里相应地位置，不过 bat 里本身也可以当作模板，应该可以很容易操作
* 至于贡献的问题……现阶段主要还是靠项目的 Collaborators 检查和进行具体的添加操作，而不是直接自己改然后 PR 上来，毕竟有些平台涉及到打包压缩之类的操作。比较好的方法就是，开新的 Issue 直接把证书的 Base64 一次性都贴上来，证书体系结构都是一样的，也比较好做记录处理和进行测试
