### ISSUE TITLE
StartSSL..

### ISSUE THREAD

**Issue by v998** [chengr28/RevokeChinaCerts#75]
先提出来...

https://pierrekim.github.io/blog/2016-02-16-why-i-stopped-using-startssl-because-of-qihoo-360.html

除了文中提到 `auth.startssl.com` `www.startssl.com` 是使用360的IP(应该是位于美国?)外，

我自已查到的的 `crl.startssl.com` `ocsp.startssl.com` IP 皆是 `210.52.217.254`  (是属于WoSign的..)，不过似乎不同地理位置的DNS会取得不同的IP...
![image](https://cloud.githubusercontent.com/assets/7825360/13071241/21b8be56-d4cd-11e5-96c6-1d53701cfd88.png)

<hr>
另外.. https://www.startssl.com/NewsDetails 提到...

> StartCom, a leading global Certificate Authority (CA) and provider of trusted identity and authentication services, launched its newly designed website just at the end of the year and announces **expansion if its activities in China.**
 
> [skipped]
 
> The new web site design and increased capabilities are the direct result of its **new R&D center opened earlier this year in Shenzhen, China. StartCom also intends to increase its activities in China with a new local customer service center Shenzhen in order to provide better localized support for this particular market.**

<hr>

也许All版可以加入StartSSL了...
不过似乎误伤实在太多...还是留待讨论吧..

**Comment by chengr28** [comment]
这个还是观察一阵子比较好……StartCom 其实本身业务还是挺广，之前 WoSign 的根证书也是他们交叉签署的，和天朝的企业合作也不奇怪，而且也不认为 StartCom 会把高级别的证书随便授权给外人，毕竟这关乎到公司的命脉

**Comment by jkldgoefgkljefogeg** [comment]
https://www.letsphish.org/?part=3

It looks like WoSign bought out StartCom

**Comment by chengr28** [comment]
Archives for https://www.letsphish.org:

https://archive.is/8bSp6
https://archive.is/QA61W
https://archive.is/Kk8XM
https://archive.is/rgvGW
https://archive.is/ygpHr

**Comment by goodbest** [comment]
Very Interesting...

**Comment by phuslu** [comment]
关注一发。GreatFire 又搞了一个大新闻。
https://news.ycombinator.com/item?id=12411870

**Comment by chengr28** [comment]
http://www.solidot.org/story?sid=49555

**Comment by Explorare** [comment]
StartCom Class 4 EV Server CA 这个证书未被列入吊销列表，请问此证书是否有吊销的需要呢？下次更新会加上么？

**Comment by chengr28** [comment]
@Explorare 这几天应该会把全部 StartCom 的 CA 全部加入到 All 版本中

**Comment by Explorare** [comment]
另外还有一个漏掉的 WoSign 的 WoSign Class 3 OV Server CA G2 也请考虑加上。辛苦了。

**Comment by chengr28** [comment]
@Explorare 证书的 PKI 体系是自上而下的，也就是说如果上级证书被吊销了，下级证书也不会再被信任。这个 `WoSign Class 3 OV Server CA G2` 的上级证书是 `Certification Authority of WoSign` 后者已经被添加进列表中，所以前者作为下级证书是不需要理会的

**Comment by Explorare** [comment]
了解。多谢。

**Comment by p3rcya** [comment]
@phuslu 不是GreatFire哎。。我个人博客。

**Comment by phuslu** [comment]
不厚道的在微博转发了一记 richard 的微博

http://m.weibo.cn/2265070380/4015398447761700

虽然觉得有点刻薄，但是王总的这个腔调实在让人想吐槽啊。

**Comment by chicheng** [comment]
墨尔本用Google DNS查
`www.startssl.com` / `auth.startssl.com`
`104.192.110.244`
QiHU 360 Inc. / Beijing Qihu Technology Company Limited
http://ipinfo.io/AS55992
查 `crl.startssl.com` `ocsp.startssl.com` 直接返回akimai的IP

**Comment by Explorare** [comment]
[Chinese CA WoSign faces revocation after issuing fake certificates of Github, Microsoft and Alibaba](http://www.percya.com/2016/08/chinese-ca-wosign-faces-revocation.html)

**Comment by Explorare** [comment]
36kr 的 CDN sta.36krcnd.com 用了 WoSign 签发的证书，我将这个域名的证书保存下来加入了受信任的根证书颁发机构，然而还是显示已吊销。求添加例外的方法。Windows + Chrome 51

**Comment by chengr28** [comment]
@Explorare 之前就说过 PKI 体系是自上而下的，根证书都被吊销了，下级的证书怎么可能还会被信任，这个和例外没有关系

**Comment by Explorare** [comment]
也就是说没办法单独让这个网站正常加载咯

**Comment by chengr28** [comment]
StartCom 的3张根证书都已经被添加到 All 版本里了

**Comment by Explorare** [comment]
辛苦了 ( ﾟ∀。)
