### ISSUE TITLE
如何备份CA证书？

### ISSUE THREAD

**Issue by kashu** [chengr28/RevokeChinaCerts#76]
我用的系统是 Xubuntu 14.04.3 LTS 64-bit
我要使用RevokeChinaCerts，你们也建议用户先做好证书的备份

可我对证书这东西不太懂，请问如何备份？
能否把详细的备份步骤告诉我，谢谢！

**Comment by kashu** [comment]
在网上翻了半天， 居然没找到如何备份Linux CA证书的方法……

**Comment by kashu** [comment]
有人知道如何备份Xubuntu里面CA的证书吗？

**Comment by chengr28** [comment]
[Lnux 版本的主页](https://github.com/chengr28/RevokeChinaCerts/tree/master/Linux) 和 [A note about SSL/TLS trusted certificate stores, and platforms (OpenSSL and GnuTLS)](https://www.happyassassin.net/2015/01/12/a-note-about-ssltls-trusted-certificate-stores-and-platforms) 都有提到证书储存文件的所在位置，因为 Linux 平台本身自由度高各发行版或应用程序并没有统一的证书系统

**Comment by kashu** [comment]
谢谢，我觉得你们可以在脚本里增加一个备份证书的函数
这样，用户会更方便，如用户只要执行 ./revoke-china-certs.sh --backup
就可以直接备份好了

**Comment by kashu** [comment]
我直接把 /etc/ssl 和 /usr/share/ca-certificates/ 这两个文件夹备份了，本身内容就很小
cp -ap /etc/ssl /etc/ssl.bak.20160219
cd /usr/share/ca-certificates/
cp -ap ca-certificates/ ca-certificates.bak.20160219

**Comment by kashu** [comment]
我把 /etc/ssl 和 /usr/share/ca-certificates/ 和 /var/lib/nssdb/ 这3个文件夹备份了
cp -ap /etc/ssl /etc/ssl.bak.20160219
cd /usr/share/ca-certificates/
cp -ap ca-certificates/ ca-certificates.bak.20160219
cd /var/lib/nssdb/
cp -ap nssdb/ nssdb.bak.20160219

**Comment by kashu** [comment]
这是脚本执行完后，做的那个测试
![](http://ww3.sinaimg.cn/large/9c4ddab1gw1f14pfgkq0oj20cj0g8dit.jpg)

**Comment by kashu** [comment]
在Chromium浏览器中，上面那些测试为红色的网站，已经打不开了

**Comment by kashu** [comment]
在Chromium浏览器中，上面那些测试为红色的网站，已经打不开了
![](http://ww2.sinaimg.cn/large/9c4ddab1jw1f14pkczlfdj20j50ejwi3.jpg)

**Comment by kashu** [comment]
但是，Firefox浏览器却依然可以打开那些网站……

这行for语句是不是有问题，执行后全部报错？这条命令具体是想做什么？  
我对bash shell脚本比较熟悉，我觉得是不是得要优化一下？
 for profile in `ls ~/.mozilla/firefox/*.default`;do
        ./revoke-china-certs.sh extended $HOME/.mozilla/firefox/$profile
    done


sed: can't read : No such file or directory
Generating ALL CRL set
Resetting CA set
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
Revoking CAs in /home/kashu/.mozilla/firefox/xulstore.json/cert{8,9}.db
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.

**Comment by kashu** [comment]
我可以确定的是，关于那个firefox的for语句，一定有错误，单独拿出来执行时，连文件都找不到
for profile in `ls ~/.mozilla/firefox/*.default`;do ls $HOME/.mozilla/firefox/$profile; done

那条命令具体是想做什么？

**Comment by ntkme** [comment]
``` bash
for profile in `ls -d ~/.mozilla/firefox/*.default`; do
  ./revoke-china-certs.sh extended "$profile"
done
```

**Comment by kashu** [comment]
@ntkme 
# 肯定不是这样的。
# 这条for语句本身就有问题，它到底是想匹配哪些文件，然后来做./revoke-china-certs.sh extended "$profile"的动作？

```
kashu:/tmp/RevokeChinaCerts-master/Linux$ for profile in `ls -d ~/.mozilla/firefox/*.default`; do ./revoke-china-certs.sh all "$profile"; done
Generating ALL CRL set
Resetting CA set
Revoking CAs in /home/kashu/.mozilla/firefox/48liz01m.default/cert{8,9}.db
certutil: could not decode certificate: SEC_ERROR_REUSED_ISSUER_AND_SERIAL: You are attempting to import a cert with the same issuer/serial as an existing cert, but that is not the same cert.
Done
sed: can't read : No such file or directory
```

执行后没有一点作用，Firefox依旧可以打开https://www.cnnic.cn/

**Comment by ntkme** [comment]
@kashi: `ls -d`: notice that `-d`. The previous one is wrong, because  of the missing `-d`.

**Comment by kashi** [comment]
Hi I'm kashi, not kashu. Suddenly I've got notification email from here. :)

At a glance I thought "kashu's ls is original? Isn't it an alias of "ls --color" or something like that?"
If so, $profile contains garbage and following revoke-china-certs.sh will fail...
This is a wild guess so I'm sorry when I'm wrong. Have a nice day anyway...

**Comment by kashu** [comment]
Thank you.
