### ISSUE TITLE
运行完 CodeSigning_All 之后似乎迅雷和百度云安装都能正常运行

### ISSUE THREAD

**Issue by kongwy** [chengr28/RevokeChinaCerts#77]
似乎是这两个证书没有包含？

- https://www.dropbox.com/s/ciat1woz630dimj/baidu.cer?dl=0
- https://www.dropbox.com/s/euwqqfugp6p7xth/thunder.cer?dl=0

**Comment by chengr28** [comment]
这两个证书 CodeSigning 里的确是没有，似乎是最近 Mcrosoft 那边说要淘汰 SHA-1 的数字签名，很多程序都把 SHA-1 和 SHA-256 的证书一起换了……刚才已经推送更新，可以试试
