### ISSUE TITLE
Linux Revoking for OpenSSL: No certsum_extended.txt

### ISSUE THREAD

**Issue by HighIO** [chengr28/RevokeChinaCerts#78]
$sudo ./cac_revoke.sh extended
**cat: certsum_extended.txt: No such file or directory**

Here is the validator.sh test:
http://paste2.org/KgbMh9dN

**Comment by phoeagon** [comment]
Try changing the following line to:
https://github.com/chengr28/RevokeChinaCerts/blob/master/Linux/cac_revoke.sh#L90

cat certsum_${1}_sorted.txt | cut -f 3 -d ' '


I don't have arch and therefore can't test though.

**Comment by HighIO** [comment]
I found it's easier to copy *.crt to `/etc/ca-certificates/trust-source/blacklist/` and run `update-ca-trust` as root.

**Comment by chengr28** [comment]
Did PR https://github.com/chengr28/RevokeChinaCerts/pull/83 fix this problem?
