### ISSUE TITLE
为什么不保留Extended版本？全部变成All版本

### ISSUE THREAD

**Issue by kang000feng** [chengr28/RevokeChinaCerts#79]
@chengr28 是建议用all版本吗？

**Comment by chengr28** [comment]
什么叫『不保留 Extended 版本』？三个版本 Base/Extended/All 一直都是可以选的

**Comment by kang000feng** [comment]
抱歉，我是说CodeSigning，刚刚下载的里面只有All版本，是建议用all版本吗？

**Comment by chengr28** [comment]
CodeSigning 和 Organization 是在清楚其目的下使用的，这边并没有任何的建议可以提供
Choice 的确是去掉了，因为随着证书数量的增加，一个一个选已经没有意义
现在推荐的做法是到 [Wiki](https://github.com/chengr28/RevokeChinaCerts/wiki/ReadMe_CodeSigning_Organization) 上，对应表中的数据将不想吊销的证书删掉，然后运行 All 版本这样

**Comment by kang000feng** [comment]
谢谢你！我知道其目的，但看了wiki有点困惑，请问CodeSigning 和 Organization的All 版本指的是CodeSigning 和 Organization各自所有可疑的证书吗？如果是的话，都删掉是比较安全的吧？

**Comment by chengr28** [comment]
这两个部分是分开的，就是说用了一边，另一边是完全不受影响
至于你说是不是全部吊销掉比较安全，这个我们无法给你回答，因为 CodeSigning + Organization 和 Online 不一样，需要清晰知道证书的用途才能使用

**Comment by kang000feng** [comment]
感谢深夜还在提供帮助
