### ISSUE TITLE
portable firefox： The certificate/key database is in an old, unsupported format.

### ISSUE THREAD

**Issue by kang000feng** [chengr28/RevokeChinaCerts#80]
下载最新的RevokeChinaCerts， 已输入profile path, firefox 版本为43.0.4，是这个版本不支持吗？

**Comment by chengr28** [comment]
那个提示大意就是版本太旧不支持，建议先更新到最新版本试试

**Comment by kang000feng** [comment]
@chengr28 更新到最新版本还是出错, 提示cannot add to token

**Comment by chengr28** [comment]
刚才已经推送了新版本……是从 Mozilla 上下载的最新版本源代码编译的 Certutil 工具，应该不会出现数据库太旧的问题，如果还是这样提示，那么应该是数据库损坏的缘故……
