### ISSUE TITLE
cnnic一周前更新了证书

### ISSUE THREAD

**Issue by aescin** [chengr28/RevokeChinaCerts#81]
才以“管理员”运行RevokeChinaCerts_Online.bat选择了“2”。
貌似cnnic没有被拉黑？是操作失误还是和cnnic在8月5号有更新证书有关？

不会截图。

**Comment by chengr28** [comment]
CNNIC 最近把自己网站的证书换成了 `DigiCert Global Root CA` 他们自己的两张证书大概是放弃了……这边项目的 Wiki 有提供 Apple 的 `CNNIC ROOT` 白名单列表可供测试

**Comment by jnozsc** [comment]
那是不是应该把 test case 里的 cnnic 去掉？
