### ISSUE TITLE
Windows提示：应用程序无法正常启动(0xc000007b)

### ISSUE THREAD

**Issue by uolcano** [chengr28/RevokeChinaCerts#82]
用管理员权限执行`RevokeChinaCerts_Online.bat`，没有错误提示就执行完确认了。

但是执行`RevokeChinaCerts_Firefox.bat`就弹出程序无法正常启动的提示，
我看黑窗提示要装ms vc++ redist 2005就去装了个[x64](https://www.microsoft.com/en-us/download/details.aspx?id=48145)版的，可是再用管理员权限运行，依旧还是这种提示，不懂哪里出错了，提示窗的title是`certutil.exe`。

虽然在系统的`certmgr`里 受信任的根证书颁发机构 下没有了CNNIC这种毒瘤，也确实都搬到了 不受信任的证书 组下，但是chrome下浏览`https://www.cnnic.cn`依然被识别为私密链接，并且证书有效。
授权结构是:
```
DigiCert
   \ DigiCert SHA2 Secure Server CA
      \ www.cnnic.cn
```
另外请问下，有没有手动删除的法子？Firefox里的DigiCert证书又不能全部完全禁用，否则MDN都是没有CSS样式渲染的。试了好久没有效方法。
并且网上找的nocnnic因为版本太旧，已经不识别Firefox了。略感无望

**Comment by chengr28** [comment]
* 关于第一个问题……窗口提示的是 `All revoking require Microsoft Visual C++ Redistributable 2015` 不是 2005 而且由于兼容性的考虑这边都是编译 x86 版本的

* 关于第二个问题……现在 CNNIC 换了 DigiCert 的证书，如果只是针对 CNNIC 这个网站，那么可以导出他们网站（签发给具体域名）的证书然后导入吊销列表，这样可以只吊销掉这张证书而不影响 DigiCert

**Comment by uolcano** [comment]
感谢回复。
第一个问题打错字了，确实装的2015，但是是x64版的。安装x86版后，`RevokeChinaCerts_Firefox.bat`可以正常运行。但是，火狐48.0 en_US，还是对www.cnnic.cn提示secure connection，浏览器数据的话用ccleaner清理了啊，不知还有哪里漏了。
第二个问题，受感动吊销以后，www.cnnic.cn确实不能上了。

**Comment by chengr28** [comment]
嗯……因为最近 CNNIC 好像放弃自己的根证书都换成 DigiCert 的了
这边只吊销了他们家的根证书，所以正常来说都可以访问
