### ISSUE TITLE
test case 清理

### ISSUE THREAD

**Issue by jnozsc** [chengr28/RevokeChinaCerts#84]
我暂时搜了一下 code base

https://mail.ztgame.com/
只在 mac 和 linux 下有

https://ibanks.bankofshanghai.com/
我也测试过不了。

我感觉是不是应该把 test case 的 list 放到 share 里？

需要的话我可以交一个 PR

**Comment by jnozsc** [comment]
好像 cnnic 网站已经不需要测试了?

https://github.com/chengr28/RevokeChinaCerts/issues/81

**Comment by chengr28** [comment]
* [ReadMe_Online](https://github.com/chengr28/RevokeChinaCerts/wiki/ReadMe_Online) 页面有全部所有被吊销证书的列表，Name 部分可以点击的都是这边找到的可供测试或者提供了相关信息的网站
* 至于提到的两个网址，经测试依旧正在服务中，所以不能去除
* macOS 的测试列表看了一下，应该只有 CNNIC 那两个是符合去除要求的

**Comment by chengr28** [comment]
这边下次更新的时候会一并把 Linux 平台和 macOS 平台的测试脚本清理一下

**Comment by jnozsc** [comment]
https://ibanks.bankofshanghai.com/ 我本身是直接打不开，是不是网站已经挂了？

https://mail.ztgame.com/ 应该保留。

我的问题是现在 mac 和 linux 管理着两个 test 列表，还是不同步的

**Comment by chengr28** [comment]
* 刚才就说过了，这个 https://ibanks.bankofshanghai.com 是没有问题的
* 关于两个平台测试列表不同步的问题，这个现阶段的话只能在更新的时候手动同步了

**Comment by jnozsc** [comment]
https://ibanks.bankofshanghai.com 我这里是 `ERR_CONNECTION_RESET`,  墙了？ 我在美国

**Comment by chengr28** [comment]
不清楚是过 GFW 被切了连接还是本身网站不提供境外服务器，这边过去是没问题的：
![Shanghai Bank SHECA](https://lh3.googleusercontent.com/mmOyJWf3ktYkbqWi0fDp0bDhT-ezbnW1ybayvGUUE9WDGFVytbgc5BtNlfabpqDRW4xBdPH_lb8-chLr-lJIYKIDohzquTFpOFrw5WwQokHOTQ_vS8ajC3QeBy2Ge17yMwbvLvn7LvuWqnSDSuupqSllI9UuAa5hTC1GFlXC0fM3xwr1X_4tgkutFTXvepVhf-w9wJN5Rfu3t98e0JtXbBznRjXjDdFkR6tKltmi2uUTGUkBZvlSPRKoSUWjFDGi73VNMtP41-jCs2IO4sdVM0diF4MmRopZ0wGFM9JnbSM4E10-wqmZDC-ZHx0jYlD0F0dv5jGQQW4quuWqZub5E-yhV-4WrNSvxhIrZdfr5cEikeUEfxAEfwy0dACDoVzqUl-l02CLiNRfHbar2z5GIRI4kCJqlp930CtmJXwtddKnLcq9OqV3fZ5RbgUIxmU1dZwwmB4_DM-yFYW7fuXu0VCHiy_F4bIjX5bLpJ8c8VjfNbQM84Sx05y2c2sEo_ye8beJLA4AFdrnAUbd4YSBiuayCuMDlTAX_ZgVQ07SKl8YqCi9u6POtGIqUzICirGAx725GJfkvkOqKOpiBNyIQXX_WbvnjUK0VqRJWegofGpREVfsCA=s0)

**Comment by jnozsc** [comment]
嗯，你这边的测试结果确实跟我不一样啊。

**Comment by yfdyh000** [comment]
https://ibanks.bankofshanghai.com/ 我也能连上。

**Comment by phoeagon** [comment]
加州親測可用

**Comment by chengr28** [comment]
OK 已经整理好测试用的脚本了
