### ISSUE TITLE
mac 下 safari 与 chrome 测试结果不一样

### ISSUE THREAD

**Issue by jnozsc** [chengr28/RevokeChinaCerts#85]
命令行测试结果 

 ~/RevokeChinaCerts/Mac   master ●  ./test-trust-settings.sh
✓ https://211.146.10.133/
✓ https://cstest.cfca.com.cn/
✓ https://cs.cfca.com.cn/
✓ https://www.sheca.com/
✗ https://evdemo.cnnic.cn/
✓ https://www.wosign.com/
✗ https://www.cnnic.cn/
? https://ibanks.bankofshanghai.com/
└── curl: (35) Server aborted the SSL handshake
? https://mail.ztgame.com/
└── curl: (28) Connection timed out after 60003 milliseconds

safari 打开  https://www.wosign.com/， 报错，ok，符合预期
chrome 打开 https://www.wosign.com/ …… 一切(不？)正常。能打开

**Comment by chengr28** [comment]
有两种可能：
* macOS 本身的证书机制有问题，之前 https://github.com/chengr28/RevokeChinaCerts/issues/65 有提到
* WoSign 的网站会根据请求的浏览器不同而发送不同的证书，一般会发送他们自己 CA 签名的证书，也可能会发送由 StartCom 交叉签署的证书，需要具体分析

**Comment by jnozsc** [comment]
问题是我已经导入 all 了啊

**Comment by chengr28** [comment]
如果是昨晚更新后的版本，那么建议看看 WoSign 的证书结构

**Comment by jnozsc** [comment]
7 小时之后猜测是 chrome 也屏蔽了…… 难道是 chrome 本身有 cache， ok to close this for now

**Comment by chengr28** [comment]
Windows 下的 Chrome 倒用的是系统自身的 SSL 缓存，不过对于 CRL 这种高优先级的操作，无论有没有缓存 Windows 都会重新检查一次，这点比较好
macOS 那边之前好像也可以，但自从说要吊销 `CNNIC ROOT` 给他们部分网站开天窗后，感觉整个系统的证书体系都被搞得乱七八糟……
