### ISSUE TITLE
[Linux] certsum_$1_sorted.txt has tabs, causing script to silently fail

### ISSUE THREAD

**Issue by TecyT** [chengr28/RevokeChinaCerts#86]
As it is right now, Linux/cac_revoke.sh#L98 uses `cut -f 3 -d ' '` to get file names from `certsum_$1.txt`. However, `certsum_$1.txt` is nonexistent, and `certsum_$1_sorted.txt` has tabs instead of spaces before the third column. As a result, the script fails silently since nothing is returned from the command.

Fix: Change the filename from `certsum_$1.txt` to `certsum_$1_sorted.txt`. Replace tabs with spaces, or use tabs with `cut(1)`.

It would probably be even better if the script is revised to fetch directly from `Shared/Certificates` like the scripts for other platforms do, to avoid the problem of the `certsum_$1_sorted.txt` files going out-of-date.

**Comment by chengr28** [comment]
Fixed.
