### ISSUE TITLE
missing vcruntime140.dll

### ISSUE THREAD

**Issue by shell909090** [chengr28/RevokeChinaCerts#87]
Under windows, I was trying to use RevokeChinaCerts_Firefox.bat. Then a dialog poped up. It's said missing vcruntime140.dll. But I'm pretty sure I have this file.
So I took a look at certutils.exe. It turns out this is a 32-version executable file. So all I need is an 32-version of vcruntime140.dll...
plz update the document so the next one will not got confused again...

**Comment by chengr28** [comment]
About this problem, there is a solution in RevokeChinaCerts_Firefox.bat description:
```
All revoking require Microsoft Visual C++ Redistributable 2015(x86)
```
