### ISSUE TITLE
win10周年版新系统，激活后只安装了最新的补丁和驱动，选择 RevokeChinaCerts_Online的All version

### ISSUE THREAD

**Issue by zasl** [chengr28/RevokeChinaCerts#88]
提示成功，想打继续清楚firefox的证书，提示我安装c+ 2015，上官方主页下载，提示此网站安全证书有问题，点击继续访问此网页(不推荐)，没有任何反应，继续用RevokeChinaCerts_Online选项4想恢复提示错误，重新启动后继续运行RevokeChinaCerts_Online的选项4，提示。。
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed
Error: Can not find a certificate matching the hash value
CertMgr Failed

RevokeChinaCerts Online batch
Done, please confirm the messages on screen.

请问如何解决

**Comment by chengr28** [comment]
如果脚本无法恢复，可以先运行位于 `Tools\Fixit` 中的 `Microsoft_Fixit_20135.diagcab` 清空所有证书数据，然后运行 `certmrg.msc` 启动证书管理器，再将不信任证书列表中所有证书全部清空，最后重启机器应该就没有问题了，这样系统的证书就会还原到初始状态
