### ISSUE TITLE
加入功能：祇驗證並列出可疑的項目？

### ISSUE THREAD

**Issue by Edditoria** [chengr28/RevokeChinaCerts#89]
謝謝你的script, 跑了 `./test-trust-settings.sh` 才發現有遺漏

請加入功能，祇驗證並列出可疑的項目？目的在於，在寫入前可以容許先了解會改動的東西

先謝

**Comment by chengr28** [comment]
看不懂这是什么功能……

**Comment by Jamesits** [comment]
dry run

**Comment by Edditoria** [comment]
yes. Dry run. Thanks.

**Comment by Explorare** [comment]
Agree.

**Comment by chengr28** [comment]
以本项目来说比较难做……主要问题是吊销证书基本都依靠第三方的工具，工具若果没有提供类似的功能，这边基本完成不了 dry run 应有的功能。或者如果有更好的方法，欢迎 pull request 上来一起看看

**Comment by wooowooo** [comment]
我同意增加这个功能. 
尚未解决为何issue被close?

**Comment by chengr28** [comment]
@wooowooo Pull request welcome.
