### ISSUE TITLE
安卓酷市场无法使用

### ISSUE THREAD

**Issue by sino1641** [chengr28/RevokeChinaCerts#90]
使用wiki用的方法后无法使用酷市场安卓客户端，网页端正常。
all,base,extened都使用过，均无法使用酷市场。
已经反馈酷安，但对方无回复。

请问有没有折中的解决方法呢？

**Comment by chengr28** [comment]
Coolapk 据说是用了 WoSign 的证书，吊销了 WoSign 估计会导致无法使用
