### ISSUE TITLE
更新操作选Online.bat还是Update.bat

### ISSUE THREAD

**Issue by Nexus2018** [chengr28/RevokeChinaCerts#92]
windows10的系统，还是在去年这个时候以管理员权限运行过RevokeChinaCerts_Online.bat。选择了2.Extended。
到刚才看到chrome和firefox都不在信任沃通的证书，才想起电脑的证书很久没管过。
现在进行更新是下载RevokeChinaCerts-master.zip后，再次运行Online.bat，还是直接运行Update.bat。毕竟一年都没更新过了。

直接Update.bat升级 CRL/证书吊销列表。会不会造成 CTL/证书信任列表 和 CRL/证书吊销列表中同时包含有同一证书。

**Comment by chengr28** [comment]
Update 是更新系统证书库的工具，Online 那个才是吊销证书的工具。至于同时存在于信任与不信任列表中时，系统会优先不信任该证书，这方面不需要担心，当然批处理本身也是会尝试把信任列表中的证书删掉的
