### ISSUE TITLE
Windows Update 同步的 pinrules.sst 文件已不存在

### ISSUE THREAD

**Issue by hyxxsfwy** [chengr28/RevokeChinaCerts#94]
目前，通过命令 ```certutil -syncWithWU "%~dp0Certificates\Other\SyncWithWU"``` 同步下来的证书文件里已经没有 pinrules.sst 这货了。```RevokeChinaCerts_Update.bat```这个脚本是不是应该更新一下？

**Comment by chengr28** [comment]
然而实际测试是有的，如果没有生成此文件建议检查一下系统配置和网络状况
