### ISSUE TITLE
怎么好像Python36装不上了

### ISSUE THREAD

**Issue by rexdf** [chengr28/RevokeChinaCerts#96]
下载 python-3.6.0-amd64.exe 然后右键 管理员运行，会弹出红窗口提示被禁止。

![python2](https://cloud.githubusercontent.com/assets/4038241/21975664/d97ec448-dc08-11e6-93b7-69b274b25ecf.PNG)

**Comment by rexdf** [comment]
哦 一直都是这个证书。我是装机之后装完Python 然后运行的这个RevokeChinaCerts

**Comment by chengr28** [comment]
StartCom 的 2 个根证书在 Online 版本的 Extended 里

**Comment by rexdf** [comment]
这不应该是CodeSigning的么？还是我理解的有问题，Online也包含软件签名？

**Comment by chengr28** [comment]
怎么说呢……Online 还是 CodeSigning 是项目这边为了方便管理进行区分而已，实际上这种内置的根证书都可以随便签发各种类型的证书，在线认证的数字签名的都可以毫无限制地签发

**Comment by rexdf** [comment]
嗯 最后把我的解决办法发一下吧，万一有其他人遇到了可以方便绕过。感觉Python应该只要解压就可以跑了。

发现比较奇怪的现象是64位14393系统上32位的Python是不会被拦截的，只有64位的用本地账户右键管理员运行会被拦截。(具体原理不了解)

Win+X，然后打开一个管理员命令行，cd到exe所在目录，然后执行exe就好了。  这样是不是说对Administrator账户无效了！？微软的这Codesign岂不是摆设了……

**Comment by yfdyh000** [comment]
@rexdf 搜索-管理计算机证书、管理用户证书，是有两个证书库的。仅部分被应用了“不信任的证书”？

**Comment by rexdf** [comment]
@yfdyh000  证书库有两个倒是在用SSTP连接添加自定义证书的时候打开过，不过我应该没折腾过里面的东西，组策略也没改过，应该只右键管理员运行过 RevokeChinaCerts_Online.bat ，选的 Extended 。意思是不是说，禁用的仅仅是Current User，而Local Machine没有禁止，所以没有效果？

另外发现全部的Python3(3.5/3.6)二进制文件，都是用这个证书签名的，比如 python36.dll python3.dll pythonw.exe，甚至 Dlls目录下面的全部 pyd文件，比如_ctypes.pyd都是用的这个证书签名的。如果OS的策略是严格禁止，那么Python3全部官方版本应该都没法跑？

**Comment by chengr28** [comment]
@rexdf Online 脚本 Current User 和 Local Machine 都有吊销的

**Comment by chengr28** [comment]
Windows 的软件数字签名策略默认不是最严格的，出现这种情况（能用 `cmd` 之类的工具绕过）就是因为这个原因。可以到组策略的 `计算机配置 - Windows设置 - 安全设置 - 软件限制策略` 里有个 `强制` 的项，进去就能看到详细的介绍
