### ISSUE TITLE
wps好像又多了一个证书

### ISSUE THREAD

**Issue by LisPerfect** [chengr28/RevokeChinaCerts#99]
-----BEGIN CERTIFICATE-----
MIIFqTCCBJGgAwIBAgIQQEva0KEedoOLEVVvr1zCWzANBgkqhkiG9w0BAQUFADCB
tDELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMR8wHQYDVQQL
ExZWZXJpU2lnbiBUcnVzdCBOZXR3b3JrMTswOQYDVQQLEzJUZXJtcyBvZiB1c2Ug
YXQgaHR0cHM6Ly93d3cudmVyaXNpZ24uY29tL3JwYSAoYykxMDEuMCwGA1UEAxMl
VmVyaVNpZ24gQ2xhc3MgMyBDb2RlIFNpZ25pbmcgMjAxMCBDQTAeFw0xNDAyMTkw
MDAwMDBaFw0xNzA0MTkyMzU5NTlaMIHuMQswCQYDVQQGEwJDTjESMBAGA1UECBMJ
R3Vhbmdkb25nMQ8wDQYDVQQHEwZaaHVoYWkxMDAuBgNVBAoUJ1podWhhaSBLaW5n
c29mdCBPZmZpY2UgU29mdHdhcmUgQ28uLEx0ZDE+MDwGA1UECxM1RGlnaXRhbCBJ
RCBDbGFzcyAzIC0gTWljcm9zb2Z0IFNvZnR3YXJlIFZhbGlkYXRpb24gdjIxFjAU
BgNVBAsUDVJEIERlcGFydG1lbnQxMDAuBgNVBAMUJ1podWhhaSBLaW5nc29mdCBP
ZmZpY2UgU29mdHdhcmUgQ28uLEx0ZDCCASAwDQYJKoZIhvcNAQEBBQADggENADCC
AQgCggEBAJWyV6wYDrFWh0xnrh9DYgL0/Aj90krFoe87GqLpFSKKbBxAAjityNwm
8Mh2GH5Ea5LajVrErWldhMPduPKixlI5fqiZ2Q50yspaBtclGcV/bjIZ8CaWetwK
Hs+qG1sjJnBRHK+KTOAaTBJjAvMrdhZdFZuhlHvh0xVaaOcoimqvB3JNiS3nbUDb
UsnYZSsr8iXMUM5UG7hyAJNaYxLip8r6fRoi5lkHukVWsqG8aPkvMxwpPZ/cZzcp
e4JT2FSNDN4Gb9tYOWOQC2T/KG9Qnr5i/53ofr8TWDG8gGxFr1LKyRB0aRTzgJ8+
emxWBUso7WjrRAAH/syLegsEr7U5CZkCAQOjggF7MIIBdzAJBgNVHRMEAjAAMA4G
A1UdDwEB/wQEAwIHgDBABgNVHR8EOTA3MDWgM6Axhi9odHRwOi8vY3NjMy0yMDEw
LWNybC52ZXJpc2lnbi5jb20vQ1NDMy0yMDEwLmNybDBEBgNVHSAEPTA7MDkGC2CG
SAGG+EUBBxcDMCowKAYIKwYBBQUHAgEWHGh0dHBzOi8vd3d3LnZlcmlzaWduLmNv
bS9ycGEwEwYDVR0lBAwwCgYIKwYBBQUHAwMwcQYIKwYBBQUHAQEEZTBjMCQGCCsG
AQUFBzABhhhodHRwOi8vb2NzcC52ZXJpc2lnbi5jb20wOwYIKwYBBQUHMAKGL2h0
dHA6Ly9jc2MzLTIwMTAtYWlhLnZlcmlzaWduLmNvbS9DU0MzLTIwMTAuY2VyMB8G
A1UdIwQYMBaAFM+Zqep7JvRLyY6P1/AFJu/j0qedMBEGCWCGSAGG+EIBAQQEAwIE
EDAWBgorBgEEAYI3AgEbBAgwBgEBAAEB/zANBgkqhkiG9w0BAQUFAAOCAQEAw1VA
qD/LxiDt2QoAx40Sv7ciaKL8cr8By1zfhn28W+UK6kjiu1OBdLzmHVJZeaSix2+8
Da35Gk/6opNmvWbmGyMWpFZX1R5eF0uicXKi84rjGjH1M66efUzA+Pdh8HIZmeWQ
m1aMdN/LhdFyYYR/311ILe6IdOwO2u6VSY/smPPdBkuRPwcBuH4zpsNY/aL6wdsa
hEM6pN8g4aDpPb0ZwTjMH4y1HNyxgdDGP7Crc70ljCprDPeNxdwVTlWwSx6708l5
r55AsJnwAhC4ncb3vuylLxduOr5qmz/gylHbQc1FJMOjA4h7w5H6YAwblSXbwtu/
8Yvy+nA6QNYcAzBrgQ==
-----END CERTIFICATE-----
![snipaste_20170305_132610](https://cloud.githubusercontent.com/assets/20284371/23584816/739da4cc-01a7-11e7-977f-87aeece6abbf.png)
*这是我手动吊销的截图*

**Comment by chengr28** [comment]
这个证书实际上 CodeSigning 是有的，可以去 https://github.com/chengr28/RevokeChinaCerts/wiki/ReadMe_CodeSigning_Organization 检查榜上有名的证书名单
